#!/usr/bin/env bash
set -euo pipefail

# Nox PR Comment — Posts inline review comments on pull requests.
# Called by action.sh after a successful scan.

readonly FINDINGS_FILE="${1:-}"
readonly MAX_COMMENTS="${2:-25}"
readonly MIN_SEVERITY="${3:-low}"

# --- Severity filtering ---

severity_rank() {
  case "$1" in
    critical) echo 0 ;;
    high)     echo 1 ;;
    medium)   echo 2 ;;
    low)      echo 3 ;;
    info)     echo 4 ;;
    *)        echo 5 ;;
  esac
}

meets_threshold() {
  local sev_rank min_rank
  sev_rank=$(severity_rank "$1")
  min_rank=$(severity_rank "$2")
  [[ "${sev_rank}" -le "${min_rank}" ]]
}

severity_badge() {
  case "$1" in
    critical) echo ":red_circle: **CRITICAL**" ;;
    high)     echo ":orange_circle: **HIGH**" ;;
    medium)   echo ":yellow_circle: **MEDIUM**" ;;
    low)      echo ":green_circle: **LOW**" ;;
    info)     echo ":blue_circle: **INFO**" ;;
    *)        echo "$1" ;;
  esac
}

# --- Validation ---

if [[ -z "${FINDINGS_FILE}" ]] || [[ ! -f "${FINDINGS_FILE}" ]]; then
  echo "No findings file found, skipping PR comments."
  exit 0
fi

if [[ -z "${GITHUB_TOKEN:-}" ]]; then
  echo "GITHUB_TOKEN not set, skipping PR comments."
  exit 0
fi

# Extract PR number from GITHUB_REF (refs/pull/123/merge).
PR_NUMBER=""
if [[ "${GITHUB_REF:-}" =~ ^refs/pull/([0-9]+)/ ]]; then
  PR_NUMBER="${BASH_REMATCH[1]}"
fi

if [[ -z "${PR_NUMBER}" ]]; then
  echo "Not in a PR context, skipping PR comments."
  exit 0
fi

REPO="${GITHUB_REPOSITORY:-}"
if [[ -z "${REPO}" ]]; then
  echo "GITHUB_REPOSITORY not set, skipping PR comments."
  exit 0
fi

# --- Parse findings and post comments ---

# Count findings by severity for summary.
declare -A SEV_COUNTS
SEV_COUNTS[critical]=0
SEV_COUNTS[high]=0
SEV_COUNTS[medium]=0
SEV_COUNTS[low]=0
SEV_COUNTS[info]=0

COMMENT_COUNT=0
TOTAL_FINDINGS=0

# Parse findings.json using grep/awk (no jq dependency).
# Each finding is extracted as: rule_id|severity|file_path|start_line|message
while IFS= read -r line; do
  TOTAL_FINDINGS=$((TOTAL_FINDINGS + 1))

  rule_id=$(echo "${line}" | sed -n 's/.*"RuleID":"\([^"]*\)".*/\1/p')
  severity=$(echo "${line}" | sed -n 's/.*"Severity":"\([^"]*\)".*/\1/p')
  file_path=$(echo "${line}" | sed -n 's/.*"FilePath":"\([^"]*\)".*/\1/p')
  start_line=$(echo "${line}" | sed -n 's/.*"StartLine":\([0-9]*\).*/\1/p')
  message=$(echo "${line}" | sed -n 's/.*"Message":"\([^"]*\)".*/\1/p')

  # Count by severity.
  if [[ -n "${severity}" ]] && [[ -v "SEV_COUNTS[${severity}]" ]]; then
    SEV_COUNTS[${severity}]=$((SEV_COUNTS[${severity}] + 1))
  fi

  # Skip if below minimum severity.
  if [[ -n "${severity}" ]] && ! meets_threshold "${severity}" "${MIN_SEVERITY}"; then
    continue
  fi

  # Skip if we've hit the max comments limit.
  if [[ "${COMMENT_COUNT}" -ge "${MAX_COMMENTS}" ]]; then
    continue
  fi

  # Skip findings without file/line (can't post inline).
  if [[ -z "${file_path}" ]] || [[ -z "${start_line}" ]] || [[ "${start_line}" == "0" ]]; then
    continue
  fi

  badge=$(severity_badge "${severity}")
  body="${badge} \`${rule_id}\`

${message}

---
<sub>Found by [nox](https://github.com/nox-hq/nox) security scanner</sub>"

  # Post inline review comment via GitHub API.
  # Use the pull request review comments endpoint for inline comments.
  COMMIT_SHA="${GITHUB_SHA:-}"

  response=$(curl -s -w "\n%{http_code}" \
    -X POST \
    -H "Authorization: Bearer ${GITHUB_TOKEN}" \
    -H "Accept: application/vnd.github+json" \
    -H "X-GitHub-Api-Version: 2022-11-28" \
    "https://api.github.com/repos/${REPO}/pulls/${PR_NUMBER}/comments" \
    -d "$(cat <<ENDJSON
{
  "body": $(echo "${body}" | python3 -c 'import json,sys; print(json.dumps(sys.stdin.read()))' 2>/dev/null || echo "\"${body}\""),
  "commit_id": "${COMMIT_SHA}",
  "path": "${file_path}",
  "line": ${start_line}
}
ENDJSON
)" 2>/dev/null || true)

  http_code=$(echo "${response}" | tail -1)
  if [[ "${http_code}" == "201" ]]; then
    COMMENT_COUNT=$((COMMENT_COUNT + 1))
  fi

done < <(grep -n '"RuleID"' "${FINDINGS_FILE}" | head -n 200)

# --- Post summary comment ---

summary_body="## Nox Security Scan Summary

| Severity | Count |
|----------|-------|
| :red_circle: Critical | ${SEV_COUNTS[critical]} |
| :orange_circle: High | ${SEV_COUNTS[high]} |
| :yellow_circle: Medium | ${SEV_COUNTS[medium]} |
| :green_circle: Low | ${SEV_COUNTS[low]} |
| :blue_circle: Info | ${SEV_COUNTS[info]} |
| **Total** | **${TOTAL_FINDINGS}** |

${COMMENT_COUNT} inline comment(s) posted (max: ${MAX_COMMENTS}, min severity: ${MIN_SEVERITY}).

---
<sub>Generated by [nox](https://github.com/nox-hq/nox) security scanner</sub>"

curl -s \
  -X POST \
  -H "Authorization: Bearer ${GITHUB_TOKEN}" \
  -H "Accept: application/vnd.github+json" \
  -H "X-GitHub-Api-Version: 2022-11-28" \
  "https://api.github.com/repos/${REPO}/issues/${PR_NUMBER}/comments" \
  -d "$(cat <<ENDJSON
{
  "body": $(echo "${summary_body}" | python3 -c 'import json,sys; print(json.dumps(sys.stdin.read()))' 2>/dev/null || echo "\"Summary: ${TOTAL_FINDINGS} findings\"")
}
ENDJSON
)" > /dev/null 2>&1 || true

echo "Posted ${COMMENT_COUNT} inline comments and summary to PR #${PR_NUMBER}."
