"""Group replayed disagreements into classes and attach the human adjudication.

The unit of adjudication is a CLASS (format, direction, the constraint the
disagreement turns on), not a witness: forty generated strings that all fail
one Bech32 checksum are one fact about nox, and counting them as forty would
make the denominator measure the generator.

Labels (assigned by reading each class's witnesses and, where needed, nox's
source and evidence ledger; see RESULT.md for the reasoning):

  defect        implementation departs from the format/proposition the rule
                claims, with a consequence a user would see
  divergence    implementation departs from the claimed format, consequence
                low or unestablished
  intentional   a deliberate design choice the reference does not share
  ref-mistake   the reference is wrong (too strict, or under-specified by its
                source); nox's behaviour is right
  unresolved    the source cannot settle it

Raw witness inputs are not written: they are credential-shaped by
construction, and committing them would make nox's own self-scan report them.
Each is identified by sha256 and regenerated by the seeded harness.

    python3 adjudicate.py <outcomes.json> <httpvalues.json> <smt_witnesses.json> > measurements.json
"""
import collections
import hashlib
import json
import sys

BOUNDARY_LEFT = {"glued-left-alnum", "glued-left-word", "inside-longer-hex"}
BOUNDARY_RIGHT = {"glued-right-alnum", "extended-1"}


def klass(o):
    f, d, v, var = o["format"], o["direction"], o["reference_violation"], o["variant"]
    leaf = var.split("/")[-1]
    det = o["origin"].startswith("detector:")
    if d == "claim-gap":
        generic = {"SEC-161", "SEC-162", "SEC-163"}
        if not set(o.get("other_rules") or []) <= generic:
            return "other-specific-rule-owns"
        if f == "jwt-jws-compact":
            return "generic-entropy-wins-dedup"
        if f == "age-secret-key":
            return "pq-hybrid-only-generic" if var.startswith("pq") else "lowercase-only-generic"
        return "other-rule-owns"
    if d == "fn":
        if f == "age-secret-key":
            return "pq-hybrid-unreported" if var.startswith("pq") else "lowercase-unreported"
        if f == "jwt-jws-compact":
            return "rfc-valid-json-shape-unreported"
        if f == "aws-sns-topic-arn":
            return "partition-unreported" if "partition-aws-" in var else "keyword-gate"
        if f == "aws-access-key-id":
            return "placeholder-filtered" if "0000000000" in o.get("input_sample", "") else "reference-under-specified"
    # fp
    if leaf in BOUNDARY_LEFT:
        return "no-left-boundary"
    if leaf in BOUNDARY_RIGHT:
        return "no-right-boundary"
    if f == "github-token":
        return "underscore-in-body" if leaf == "underscore-in-body" else "length-unbounded"
    if f == "jwt-jws-compact":
        if v == "unsecured":
            return "unsecured-jwt-reported"
        if leaf in ("padded-signature", "four-segments"):
            return "reference-tokenisation-too-strict"
        return "structure-unvalidated"
    if f == "pem-private-key":
        if leaf in ("end-label-mismatch", "end-missing"):
            return "reference-format-not-proposition"
        if leaf == "body-truncated":
            return "partial-key-material"
        return "structure-unvalidated"
    if f == "pypi-api-token":
        if leaf in ("truncated-half", "truncated-1"):
            return "partial-token"
        if leaf == "std-base64":
            return "base64-variant"
        return "structure-unvalidated"
    if f == "age-secret-key":
        return "checksum-unvalidated"
    if f == "aws-access-key-id":
        return "undocumented-prefix"
    if f == "aws-sns-topic-arn":
        return "literal-prefix-no-arn"
    return "other"


LABELS = {
    ("age-secret-key", "fn", "pq-hybrid-unreported"): "defect",
    ("age-secret-key", "claim-gap", "pq-hybrid-only-generic"): "defect",
    ("age-secret-key", "claim-gap", "lowercase-only-generic"): "divergence",
    ("age-secret-key", "fn", "lowercase-unreported"): "divergence",
    ("age-secret-key", "fp", "checksum-unvalidated"): "divergence",
    ("age-secret-key", "fp", "no-left-boundary"): "divergence",
    ("age-secret-key", "fp", "no-right-boundary"): "divergence",
    ("jwt-jws-compact", "claim-gap", "generic-entropy-wins-dedup"): "defect",
    ("jwt-jws-compact", "fn", "rfc-valid-json-shape-unreported"): "divergence",
    ("jwt-jws-compact", "claim-gap", "other-specific-rule-owns"): "intentional",
    ("jwt-jws-compact", "fp", "structure-unvalidated"): "intentional",
    ("jwt-jws-compact", "fp", "no-left-boundary"): "divergence",
    ("jwt-jws-compact", "fp", "unsecured-jwt-reported"): "unresolved",
    ("jwt-jws-compact", "fp", "reference-tokenisation-too-strict"): "ref-mistake",
    ("aws-sns-topic-arn", "fn", "partition-unreported"): "defect",
    ("aws-sns-topic-arn", "fn", "keyword-gate"): "unresolved",
    ("aws-sns-topic-arn", "fp", "literal-prefix-no-arn"): "divergence",
    ("aws-access-key-id", "fn", "reference-under-specified"): "ref-mistake",
    ("aws-access-key-id", "fn", "placeholder-filtered"): "ref-mistake",
    ("aws-access-key-id", "fp", "undocumented-prefix"): "unresolved",
    ("aws-access-key-id", "fp", "no-left-boundary"): "divergence",
    ("github-token", "fp", "no-left-boundary"): "divergence",
    ("github-token", "fp", "no-right-boundary"): "divergence",
    ("github-token", "fp", "length-unbounded"): "divergence",
    ("github-token", "fp", "underscore-in-body"): "divergence",
    ("twilio-api-key-sid", "fp", "no-left-boundary"): "divergence",
    ("twilio-api-key-sid", "fp", "no-right-boundary"): "divergence",
    ("pypi-api-token", "fp", "structure-unvalidated"): "intentional",
    ("pypi-api-token", "fp", "partial-token"): "intentional",
    ("pypi-api-token", "fp", "base64-variant"): "intentional",
    ("pypi-api-token", "fp", "no-left-boundary"): "divergence",
    ("pypi-api-token", "fp", "no-right-boundary"): "intentional",
    ("pem-private-key", "fp", "structure-unvalidated"): "intentional",
    ("pem-private-key", "fp", "partial-key-material"): "intentional",
    ("pem-private-key", "fp", "reference-format-not-proposition"): "ref-mistake",
}

HTTP_LABELS = {
    "SEC-335": ("defect", "bare 40-hex alternative gated by file keyword: any SHA-1 (ETag, git commit) in a file naming Sourcegraph"),
    "SEC-421": ("unresolved", "any UUID in a file naming azure_client; whether a client ID belongs in a credential scanner is a proposition question (deviance research, class 3)"),
    "SEC-161": ("intentional", "generic heuristic; a credential word anywhere on the line qualifies the value, so an ETag beside a key NAMED like a credential is reported"),
}


def h(s):
    return hashlib.sha256(s.encode()).hexdigest()[:16]


def main():
    outcomes = json.load(open(sys.argv[1]))
    httpv = json.load(open(sys.argv[2]))
    smt = json.load(open(sys.argv[3]))

    totals = collections.Counter(o["direction"] for o in outcomes)
    classes = collections.OrderedDict()
    for o in outcomes:
        if o["direction"] == "agree":
            continue
        o["input_sample"] = o["input"]
        k = (o["format"], o["direction"], klass(o))
        c = classes.setdefault(k, {"format": k[0], "direction": k[1], "class": k[2],
                                   "witnesses": 0, "replayed": 0, "hosts": set(),
                                   "rules": set(), "origins": set(), "inputs": []})
        c["witnesses"] += 1
        c["replayed"] += 1 if o.get("replayed") else 0
        c["hosts"].add(o["host"])
        c["rules"].update(o.get("claimed_rules") or [])
        c["rules"].update(o.get("other_rules") or [])
        c["origins"].add(o["origin"].split(":")[0])
        c["inputs"].append(h(o["input"]))
    rows = []
    for k, c in classes.items():
        rows.append({**c, "hosts": sorted(c["hosts"]), "rules": sorted(c["rules"]),
                     "origins": sorted(c["origins"]), "inputs": sorted(set(c["inputs"])),
                     "label": LABELS.get(k, "UNLABELLED")})

    http_rows = collections.OrderedDict()
    for w in httpv["witnesses"]:
        for r in w["Rules"]:
            e = http_rows.setdefault(r, {"rule": r, "witnesses": 0, "replayed": 0, "shapes": set(), "kinds": set()})
            e["witnesses"] += 1
            e["replayed"] += 1 if w["Replayed"] else 0
            e["shapes"].add(w["Shape"])
            e["kinds"].add(w["Kind"])
    http_out = [{**e, "shapes": sorted(e["shapes"]), "kinds": sorted(e["kinds"]),
                 "label": HTTP_LABELS[r][0], "note": HTTP_LABELS[r][1]} for r, e in http_rows.items()]

    smt_out = [{**{k: v for k, v in s.items() if k != "input"}, "input_sha256_16": h(s["input"])} for s in smt]

    json.dump({
        "harness": {"candidates": len(outcomes), "by_direction": dict(totals)},
        "classes": rows,
        "http_values": {"vendor_names": httpv["vendor_names"], "files": httpv["files"], "by_rule": http_out},
        "smt_against_nox": smt_out,
    }, sys.stdout, indent=1)
    for r in rows:
        print(f'{r["label"]:<12} {r["format"]:<20} {r["direction"]:<9} {r["class"]:<36} w={r["witnesses"]:<3} rep={r["replayed"]:<3} {",".join(r["rules"])}', file=sys.stderr)


if __name__ == "__main__":
    main()
