package iac

import (
	"github.com/nox-hq/nox/core/findings"
	"github.com/nox-hq/nox/core/rules"
)

// builtinAnsibleRules returns built-in Ansible IaC security rules (IAC-186 to IAC-230).
func builtinAnsibleRules() []rules.Rule {
	defs := []iacRule{
		// =================================================================
		// Privilege Escalation (IAC-186 to IAC-192)
		// =================================================================
		{
			id: "IAC-186", severity: findings.SeverityHigh, confidence: findings.ConfidenceMedium,
			pattern:      `become:\s*(?:true|yes)`,
			description:  "Ansible playbook uses become without specifying become_user",
			cwe:          "CWE-250",
			keywords:     []string{"become"},
			filePatterns: []string{"*.yml", "*.yaml"},
			tags:         []string{"iac", "ansible", "privilege"},
			remediation:  "Always specify become_user explicitly when using privilege escalation. Avoid escalating to root unless absolutely necessary. Use the least privileged user required for the task.",
			references:   []string{"https://cwe.mitre.org/data/definitions/250.html", "https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_privilege_escalation.html"},
		},
		{
			id: "IAC-187", severity: findings.SeverityHigh, confidence: findings.ConfidenceHigh,
			pattern:      `(?i)become_user:\s*['"]?root['"]?`,
			description:  "Ansible task escalates to root user",
			cwe:          "CWE-250",
			keywords:     []string{"become_user", "root"},
			filePatterns: []string{"*.yml", "*.yaml"},
			tags:         []string{"iac", "ansible", "privilege"},
			remediation:  "Use a dedicated service account instead of root. Create a non-root user with only the permissions required for the task and use become_user to escalate to that user.",
			references:   []string{"https://cwe.mitre.org/data/definitions/250.html", "https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_privilege_escalation.html"},
		},
		{
			id: "IAC-188", severity: findings.SeverityMedium, confidence: findings.ConfidenceMedium,
			pattern:      `(?i)become_method:\s*['"]?su['"]?`,
			description:  "Ansible uses su for privilege escalation (prefer sudo)",
			cwe:          "CWE-250",
			keywords:     []string{"become_method", "su"},
			filePatterns: []string{"*.yml", "*.yaml"},
			tags:         []string{"iac", "ansible", "privilege"},
			remediation:  "Use sudo instead of su for privilege escalation. Sudo provides better audit logging, granular permission control, and does not require sharing the target user password.",
			references:   []string{"https://cwe.mitre.org/data/definitions/250.html"},
		},
		{
			id: "IAC-189", severity: findings.SeverityHigh, confidence: findings.ConfidenceMedium,
			pattern:      `(?i)become_flags:.*NOPASSWD`,
			description:  "Ansible become with NOPASSWD flag",
			cwe:          "CWE-250",
			keywords:     []string{"become_flags", "NOPASSWD"},
			filePatterns: []string{"*.yml", "*.yaml"},
			tags:         []string{"iac", "ansible", "privilege"},
			remediation:  "Avoid NOPASSWD in become_flags. Configure sudoers with password requirements and use Ansible Vault for become passwords. NOPASSWD weakens the security boundary of privilege escalation.",
			references:   []string{"https://cwe.mitre.org/data/definitions/250.html"},
		},
		{
			id: "IAC-190", severity: findings.SeverityCritical, confidence: findings.ConfidenceHigh,
			pattern:      `(?i)ansible_become_pass\s*[:=]`,
			description:  "Ansible become password in plaintext",
			cwe:          "CWE-798",
			keywords:     []string{"ansible_become_pass"},
			filePatterns: []string{"*.yml", "*.yaml"},
			tags:         []string{"iac", "ansible", "privilege", "secrets"},
			remediation:  "Use Ansible Vault to encrypt become passwords or prompt for them at runtime with --ask-become-pass. Never store plaintext passwords in inventory or playbook files.",
			references:   []string{"https://cwe.mitre.org/data/definitions/798.html", "https://docs.ansible.com/ansible/latest/vault_guide/index.html"},
		},
		{
			id: "IAC-191", severity: findings.SeverityCritical, confidence: findings.ConfidenceHigh,
			pattern:      `(?i)ansible_ssh_pass\s*[:=]`,
			description:  "Ansible SSH password in plaintext",
			cwe:          "CWE-798",
			keywords:     []string{"ansible_ssh_pass"},
			filePatterns: []string{"*.yml", "*.yaml"},
			tags:         []string{"iac", "ansible", "secrets"},
			remediation:  "Use SSH key-based authentication instead of passwords. If passwords are required, encrypt them with Ansible Vault or use --ask-pass at runtime.",
			references:   []string{"https://cwe.mitre.org/data/definitions/798.html", "https://docs.ansible.com/ansible/latest/vault_guide/index.html"},
		},
		{
			id: "IAC-192", severity: findings.SeverityCritical, confidence: findings.ConfidenceHigh,
			pattern:      `(?i)ansible_password\s*[:=]`,
			description:  "Ansible password variable set in plaintext",
			cwe:          "CWE-798",
			keywords:     []string{"ansible_password"},
			filePatterns: []string{"*.yml", "*.yaml"},
			tags:         []string{"iac", "ansible", "secrets"},
			remediation:  "Encrypt password variables with Ansible Vault. Use 'ansible-vault encrypt_string' for inline encryption or store secrets in a vault-encrypted vars file.",
			references:   []string{"https://cwe.mitre.org/data/definitions/798.html", "https://docs.ansible.com/ansible/latest/vault_guide/index.html"},
		},

		// =================================================================
		// Shell/Command Module (IAC-193 to IAC-198)
		// =================================================================
		{
			id: "IAC-193", severity: findings.SeverityMedium, confidence: findings.ConfidenceLow,
			pattern:      `(?i)shell:\s`,
			description:  "Ansible task uses shell module (prefer command or dedicated module)",
			cwe:          "CWE-78",
			keywords:     []string{"shell"},
			filePatterns: []string{"*.yml", "*.yaml"},
			tags:         []string{"iac", "ansible", "best-practice"},
			remediation:  "Use the command module or a dedicated Ansible module instead of shell. The shell module invokes /bin/sh and is susceptible to shell injection if variables are not properly quoted.",
			references:   []string{"https://cwe.mitre.org/data/definitions/78.html", "https://docs.ansible.com/ansible/latest/collections/ansible/builtin/shell_module.html"},
		},
		{
			id: "IAC-194", severity: findings.SeverityMedium, confidence: findings.ConfidenceMedium,
			pattern:      `(?i)raw:\s`,
			description:  "Ansible task uses raw module",
			cwe:          "CWE-78",
			keywords:     []string{"raw"},
			filePatterns: []string{"*.yml", "*.yaml"},
			tags:         []string{"iac", "ansible", "best-practice"},
			remediation:  "Replace the raw module with a dedicated Ansible module when possible. The raw module bypasses the Ansible module subsystem and runs commands directly via SSH, offering no idempotency or input sanitization.",
			references:   []string{"https://cwe.mitre.org/data/definitions/78.html", "https://docs.ansible.com/ansible/latest/collections/ansible/builtin/raw_module.html"},
		},
		{
			id: "IAC-195", severity: findings.SeverityLow, confidence: findings.ConfidenceLow,
			pattern:      `(?i)command:.*\|`,
			description:  "Ansible command module with pipe (use shell module explicitly)",
			cwe:          "CWE-78",
			keywords:     []string{"command"},
			filePatterns: []string{"*.yml", "*.yaml"},
			tags:         []string{"iac", "ansible", "best-practice"},
			remediation:  "The command module does not process pipes. If piping is needed, use the shell module explicitly so the intent is clear and reviewers can assess shell injection risk.",
			references:   []string{"https://cwe.mitre.org/data/definitions/78.html"},
		},
		{
			id: "IAC-196", severity: findings.SeverityHigh, confidence: findings.ConfidenceMedium,
			pattern:      `(?i)shell:.*rm\s+-rf`,
			description:  "Ansible shell task with dangerous rm -rf command",
			cwe:          "CWE-78",
			keywords:     []string{"shell", "rm"},
			filePatterns: []string{"*.yml", "*.yaml"},
			tags:         []string{"iac", "ansible", "destructive"},
			remediation:  "Use the file module with state=absent instead of shell rm -rf. The file module is idempotent and safer. If shell is required, add guards such as 'when' conditions and validate paths.",
			references:   []string{"https://cwe.mitre.org/data/definitions/78.html"},
		},
		{
			id: "IAC-197", severity: findings.SeverityCritical, confidence: findings.ConfidenceHigh,
			pattern:      `(?i)(?:shell|command|raw):.*curl.*\|\s*(?:bash|sh)`,
			description:  "Ansible task pipes curl to shell",
			cwe:          "CWE-829",
			keywords:     []string{"curl", "bash", "shell"},
			filePatterns: []string{"*.yml", "*.yaml"},
			tags:         []string{"iac", "ansible", "supply-chain"},
			remediation:  "Download the script with get_url, verify its checksum, then execute it. Piping curl output to a shell skips integrity verification and is vulnerable to man-in-the-middle and supply-chain attacks.",
			references:   []string{"https://cwe.mitre.org/data/definitions/829.html"},
		},
		{
			id: "IAC-198", severity: findings.SeverityHigh, confidence: findings.ConfidenceHigh,
			pattern:      `(?i)shell:.*chmod\s+777`,
			description:  "Ansible shell sets world-writable permissions",
			cwe:          "CWE-732",
			keywords:     []string{"shell", "chmod", "777"},
			filePatterns: []string{"*.yml", "*.yaml"},
			tags:         []string{"iac", "ansible", "permission"},
			remediation:  "Use the file module with an appropriate mode (e.g., 0755 or 0644) instead of shell chmod. World-writable permissions (777) allow any user to modify the file.",
			references:   []string{"https://cwe.mitre.org/data/definitions/732.html"},
		},

		// =================================================================
		// Logging/Security (IAC-199 to IAC-205)
		// =================================================================
		{
			id: "IAC-199", severity: findings.SeverityMedium, confidence: findings.ConfidenceHigh,
			pattern:      `no_log:\s*(?:false|no)`,
			description:  "Ansible task explicitly disables no_log",
			cwe:          "CWE-532",
			keywords:     []string{"no_log"},
			filePatterns: []string{"*.yml", "*.yaml"},
			tags:         []string{"iac", "ansible", "logging"},
			remediation:  "Remove no_log: false or set it to true for tasks that handle sensitive data. Disabling no_log causes passwords, tokens, and other secrets to appear in Ansible output and logs.",
			references:   []string{"https://cwe.mitre.org/data/definitions/532.html", "https://docs.ansible.com/ansible/latest/reference_appendices/logging.html"},
		},
		{
			id: "IAC-200", severity: findings.SeverityMedium, confidence: findings.ConfidenceLow,
			pattern:      `(?i)(?:password|secret|token|key)\s*:(?!.*no_log)`,
			description:  "Ansible task with sensitive variable without no_log",
			cwe:          "CWE-532",
			keywords:     []string{"password", "secret", "token", "key"},
			filePatterns: []string{"*.yml", "*.yaml"},
			tags:         []string{"iac", "ansible", "logging"},
			remediation:  "Add no_log: true to tasks that reference sensitive variables such as passwords, secrets, tokens, or keys. This prevents credential leakage in Ansible output.",
			references:   []string{"https://cwe.mitre.org/data/definitions/532.html"},
		},
		{
			id: "IAC-201", severity: findings.SeverityMedium, confidence: findings.ConfidenceHigh,
			pattern:      `ignore_errors:\s*(?:true|yes)`,
			description:  "Ansible task ignores errors",
			cwe:          "CWE-755",
			keywords:     []string{"ignore_errors"},
			filePatterns: []string{"*.yml", "*.yaml"},
			tags:         []string{"iac", "ansible", "error-handling"},
			remediation:  "Use failed_when with specific conditions instead of ignore_errors. Blanket error suppression can mask security failures, failed permission changes, or broken configurations.",
			references:   []string{"https://cwe.mitre.org/data/definitions/755.html"},
		},
		{
			id: "IAC-202", severity: findings.SeverityMedium, confidence: findings.ConfidenceMedium,
			pattern:      `failed_when:\s*false`,
			description:  "Ansible task never fails (failed_when: false)",
			cwe:          "CWE-755",
			keywords:     []string{"failed_when"},
			filePatterns: []string{"*.yml", "*.yaml"},
			tags:         []string{"iac", "ansible", "error-handling"},
			remediation:  "Replace failed_when: false with specific failure conditions. Unconditionally suppressing failures hides real errors and can lead to partially configured or insecure systems.",
			references:   []string{"https://cwe.mitre.org/data/definitions/755.html"},
		},
		{
			id: "IAC-203", severity: findings.SeverityHigh, confidence: findings.ConfidenceHigh,
			pattern:      `(?i)validate_certs:\s*(?:false|no|False|No)`,
			description:  "Ansible task disables certificate validation",
			cwe:          "CWE-295",
			keywords:     []string{"validate_certs"},
			filePatterns: []string{"*.yml", "*.yaml"},
			tags:         []string{"iac", "ansible", "transport-security"},
			remediation:  "Enable certificate validation by removing validate_certs: false or setting it to true. Install the required CA certificates on the target host if custom CAs are in use.",
			references:   []string{"https://cwe.mitre.org/data/definitions/295.html"},
		},
		{
			id: "IAC-204", severity: findings.SeverityLow, confidence: findings.ConfidenceLow,
			pattern:      `(?i)check_mode:\s*(?:false|no)`,
			description:  "Ansible task disables check mode",
			cwe:          "CWE-693",
			keywords:     []string{"check_mode"},
			filePatterns: []string{"*.yml", "*.yaml"},
			tags:         []string{"iac", "ansible", "best-practice"},
			remediation:  "Ensure check_mode: false is intentional. Consider allowing check mode for dry-run testing. Disabling check mode prevents safe validation of playbook changes before applying them.",
			references:   []string{"https://cwe.mitre.org/data/definitions/693.html"},
		},
		{
			id: "IAC-205", severity: findings.SeverityLow, confidence: findings.ConfidenceLow,
			pattern:      `(?i)gather_facts:\s*(?:false|no)`,
			description:  "Ansible play disables fact gathering",
			cwe:          "CWE-693",
			keywords:     []string{"gather_facts"},
			filePatterns: []string{"*.yml", "*.yaml"},
			tags:         []string{"iac", "ansible", "best-practice"},
			remediation:  "Ensure disabling fact gathering is intentional. Facts provide host information used by conditional tasks and security-related configurations. Disable only when performance is critical and facts are not needed.",
			references:   []string{"https://cwe.mitre.org/data/definitions/693.html"},
		},

		// =================================================================
		// File Permissions (IAC-206 to IAC-210)
		// =================================================================
		{
			id: "IAC-206", severity: findings.SeverityHigh, confidence: findings.ConfidenceHigh,
			pattern:      `(?i)mode:\s*['"]?0?777['"]?`,
			description:  "Ansible file with world-writable permissions (777)",
			cwe:          "CWE-732",
			keywords:     []string{"mode", "777"},
			filePatterns: []string{"*.yml", "*.yaml"},
			tags:         []string{"iac", "ansible", "permission"},
			remediation:  "Use the most restrictive permissions possible. For executables use 0755, for data files use 0644, and for sensitive files use 0600. World-writable permissions allow any user to modify the file.",
			references:   []string{"https://cwe.mitre.org/data/definitions/732.html"},
		},
		{
			id: "IAC-207", severity: findings.SeverityHigh, confidence: findings.ConfidenceHigh,
			pattern:      `(?i)mode:\s*['"]?0?666['"]?`,
			description:  "Ansible file with world-writable permissions (666)",
			cwe:          "CWE-732",
			keywords:     []string{"mode", "666"},
			filePatterns: []string{"*.yml", "*.yaml"},
			tags:         []string{"iac", "ansible", "permission"},
			remediation:  "Use the most restrictive permissions possible. For data files use 0644 and for sensitive files use 0600. Mode 666 allows any user to read and write the file.",
			references:   []string{"https://cwe.mitre.org/data/definitions/732.html"},
		},
		{
			id: "IAC-208", severity: findings.SeverityHigh, confidence: findings.ConfidenceMedium,
			pattern:      `(?i)(?:private_key|\.pem|\.key|credentials).*mode:\s*['"]?0?[67][0-9][0-9]`,
			description:  "Sensitive file with overly permissive mode",
			cwe:          "CWE-732",
			keywords:     []string{"private_key", "pem", "key", "credentials", "mode"},
			filePatterns: []string{"*.yml", "*.yaml"},
			tags:         []string{"iac", "ansible", "permission"},
			remediation:  "Set sensitive files (private keys, PEM files, credentials) to mode 0600 or 0400. These files should only be readable by the owning user.",
			references:   []string{"https://cwe.mitre.org/data/definitions/732.html"},
		},
		{
			id: "IAC-209", severity: findings.SeverityLow, confidence: findings.ConfidenceLow,
			pattern:      `(?i)file:.*state:\s*absent`,
			description:  "Ansible file deletion task",
			cwe:          "CWE-693",
			keywords:     []string{"file", "absent"},
			filePatterns: []string{"*.yml", "*.yaml"},
			tags:         []string{"iac", "ansible", "destructive"},
			remediation:  "Verify file deletion tasks target the correct paths and include appropriate guards. Use 'when' conditions to prevent accidental deletion in unintended environments.",
			references:   []string{"https://cwe.mitre.org/data/definitions/693.html"},
		},
		{
			id: "IAC-210", severity: findings.SeverityMedium, confidence: findings.ConfidenceLow,
			pattern:      `(?i)copy:.*owner:\s*['"]?root['"]?`,
			description:  "Ansible copy with root ownership",
			cwe:          "CWE-250",
			keywords:     []string{"copy", "owner", "root"},
			filePatterns: []string{"*.yml", "*.yaml"},
			tags:         []string{"iac", "ansible", "privilege"},
			remediation:  "Use a dedicated service account as the file owner instead of root. Root-owned files combined with group or world permissions can create privilege escalation paths.",
			references:   []string{"https://cwe.mitre.org/data/definitions/250.html"},
		},

		// =================================================================
		// Galaxy/Dependencies (IAC-211 to IAC-215)
		// =================================================================
		{
			id: "IAC-211", severity: findings.SeverityMedium, confidence: findings.ConfidenceMedium,
			pattern:      `(?i)src:\s*['"]?[a-zA-Z0-9_.-]+\s*$`,
			description:  "Ansible Galaxy role without version pin",
			cwe:          "CWE-829",
			keywords:     []string{"src"},
			filePatterns: []string{"*.yml", "*.yaml"},
			tags:         []string{"iac", "ansible", "supply-chain"},
			remediation:  "Pin Ansible Galaxy roles to a specific version using the 'version' field in requirements.yml. Unpinned roles can silently update to compromised or incompatible versions.",
			references:   []string{"https://cwe.mitre.org/data/definitions/829.html", "https://docs.ansible.com/ansible/latest/galaxy/user_guide.html"},
		},
		{
			id: "IAC-212", severity: findings.SeverityMedium, confidence: findings.ConfidenceMedium,
			pattern:      `(?i)src:\s*['"]?https?://`,
			description:  "Ansible role loaded from URL",
			cwe:          "CWE-829",
			keywords:     []string{"src", "http"},
			filePatterns: []string{"*.yml", "*.yaml"},
			tags:         []string{"iac", "ansible", "supply-chain"},
			remediation:  "Use Ansible Galaxy or a private Galaxy server for role distribution instead of direct URLs. If URL-based roles are required, pin to a specific commit or tag and verify checksums.",
			references:   []string{"https://cwe.mitre.org/data/definitions/829.html"},
		},
		{
			id: "IAC-213", severity: findings.SeverityHigh, confidence: findings.ConfidenceHigh,
			pattern:      `(?i)src:\s*['"]?git\+http://`,
			description:  "Ansible role loaded over insecure HTTP git",
			cwe:          "CWE-829",
			keywords:     []string{"src", "git", "http"},
			filePatterns: []string{"*.yml", "*.yaml"},
			tags:         []string{"iac", "ansible", "supply-chain", "transport-security"},
			remediation:  "Use git+https:// or git+ssh:// for role sources. Fetching roles over plain HTTP allows man-in-the-middle attacks that can inject malicious code into the role.",
			references:   []string{"https://cwe.mitre.org/data/definitions/829.html"},
		},
		{
			id: "IAC-214", severity: findings.SeverityMedium, confidence: findings.ConfidenceLow,
			pattern:      `(?i)name:\s*['"]?[a-z_]+\.[a-z_]+['"]?\s*$`,
			description:  "Ansible collection without version pin",
			cwe:          "CWE-829",
			keywords:     []string{"name", "collections"},
			filePatterns: []string{"*.yml", "*.yaml"},
			tags:         []string{"iac", "ansible", "supply-chain"},
			remediation:  "Pin Ansible collections to a specific version in requirements.yml. Use 'version: \">=1.0.0,<2.0.0\"' to constrain updates while allowing patch releases.",
			references:   []string{"https://cwe.mitre.org/data/definitions/829.html"},
		},
		{
			id: "IAC-215", severity: findings.SeverityHigh, confidence: findings.ConfidenceHigh,
			pattern:      `(?i)galaxy_server:\s*['"]?http://`,
			description:  "Ansible Galaxy server using HTTP",
			cwe:          "CWE-319",
			keywords:     []string{"galaxy_server", "http"},
			filePatterns: []string{"*.yml", "*.yaml"},
			tags:         []string{"iac", "ansible", "transport-security"},
			remediation:  "Use HTTPS for Galaxy server URLs. Communicating with Galaxy over plaintext HTTP exposes authentication tokens and downloaded role content to interception.",
			references:   []string{"https://cwe.mitre.org/data/definitions/319.html"},
		},

		// =================================================================
		// Firewall/Network (IAC-216 to IAC-220)
		// =================================================================
		{
			id: "IAC-216", severity: findings.SeverityMedium, confidence: findings.ConfidenceMedium,
			pattern:      `(?i)ufw:.*rule:\s*['"]?allow['"]?.*port:\s*['"]?22['"]?`,
			description:  "Ansible UFW allows SSH from any source",
			cwe:          "CWE-284",
			keywords:     []string{"ufw", "allow", "22"},
			filePatterns: []string{"*.yml", "*.yaml"},
			tags:         []string{"iac", "ansible", "network"},
			remediation:  "Restrict SSH access to specific source IP ranges using the 'from_ip' parameter. Allowing SSH from any source exposes the host to brute-force attacks from the internet.",
			references:   []string{"https://cwe.mitre.org/data/definitions/284.html"},
		},
		{
			id: "IAC-217", severity: findings.SeverityMedium, confidence: findings.ConfidenceMedium,
			pattern:      `(?i)firewalld:.*service:\s*['"]?ssh['"]?.*permanent:\s*yes`,
			description:  "Ansible firewalld permanently opens SSH",
			cwe:          "CWE-284",
			keywords:     []string{"firewalld", "ssh", "permanent"},
			filePatterns: []string{"*.yml", "*.yaml"},
			tags:         []string{"iac", "ansible", "network"},
			remediation:  "Use firewalld rich rules to restrict SSH to specific source addresses or networks. Permanently allowing SSH from all sources increases the attack surface.",
			references:   []string{"https://cwe.mitre.org/data/definitions/284.html"},
		},
		{
			id: "IAC-218", severity: findings.SeverityMedium, confidence: findings.ConfidenceMedium,
			pattern:      `(?i)iptables:.*-j\s*ACCEPT.*--dport\s*(?:22|3389)`,
			description:  "Ansible iptables allows remote access port",
			cwe:          "CWE-284",
			keywords:     []string{"iptables", "ACCEPT", "dport"},
			filePatterns: []string{"*.yml", "*.yaml"},
			tags:         []string{"iac", "ansible", "network"},
			remediation:  "Add source address restrictions (-s) to iptables rules for remote access ports. Use a VPN or bastion host for administrative access instead of exposing ports directly.",
			references:   []string{"https://cwe.mitre.org/data/definitions/284.html"},
		},
		{
			id: "IAC-219", severity: findings.SeverityHigh, confidence: findings.ConfidenceHigh,
			pattern:      `(?i)ufw:.*state:\s*['"]?disabled['"]?`,
			description:  "Ansible task disables UFW firewall",
			cwe:          "CWE-693",
			keywords:     []string{"ufw", "disabled"},
			filePatterns: []string{"*.yml", "*.yaml"},
			tags:         []string{"iac", "ansible", "network"},
			remediation:  "Do not disable UFW in production. If firewall migration is needed, enable the replacement firewall before disabling UFW to avoid leaving the host unprotected.",
			references:   []string{"https://cwe.mitre.org/data/definitions/693.html"},
		},
		{
			id: "IAC-220", severity: findings.SeverityHigh, confidence: findings.ConfidenceHigh,
			pattern:      `(?i)selinux:.*state:\s*['"]?disabled['"]?`,
			description:  "Ansible task disables SELinux",
			cwe:          "CWE-693",
			keywords:     []string{"selinux", "disabled"},
			filePatterns: []string{"*.yml", "*.yaml"},
			tags:         []string{"iac", "ansible", "security"},
			remediation:  "Keep SELinux in enforcing mode. If applications fail, set SELinux to permissive mode temporarily to identify required policy changes, then create custom policies instead of disabling SELinux entirely.",
			references:   []string{"https://cwe.mitre.org/data/definitions/693.html"},
		},

		// =================================================================
		// Hardcoded Values (IAC-221 to IAC-225)
		// =================================================================
		{
			id: "IAC-221", severity: findings.SeverityCritical, confidence: findings.ConfidenceMedium,
			pattern:      `(?i)(?:mysql|postgres|mongo)_(?:user|password|pass)\s*:\s*['"][^{'"]+['"]`,
			description:  "Ansible hardcoded database credentials",
			cwe:          "CWE-798",
			keywords:     []string{"mysql", "postgres", "mongo", "password"},
			filePatterns: []string{"*.yml", "*.yaml"},
			tags:         []string{"iac", "ansible", "secrets"},
			remediation:  "Store database credentials in Ansible Vault or an external secrets manager (HashiCorp Vault, AWS Secrets Manager). Reference them as vault-encrypted variables instead of plaintext values.",
			references:   []string{"https://cwe.mitre.org/data/definitions/798.html", "https://docs.ansible.com/ansible/latest/vault_guide/index.html"},
		},
		{
			id: "IAC-222", severity: findings.SeverityHigh, confidence: findings.ConfidenceMedium,
			pattern:      `(?i)api_key\s*:\s*['"][A-Za-z0-9]{16,}['"]`,
			description:  "Ansible hardcoded API key",
			cwe:          "CWE-798",
			keywords:     []string{"api_key"},
			filePatterns: []string{"*.yml", "*.yaml"},
			tags:         []string{"iac", "ansible", "secrets"},
			remediation:  "Store API keys in Ansible Vault or an external secrets manager. Use lookup plugins to retrieve secrets at runtime instead of embedding them in playbooks.",
			references:   []string{"https://cwe.mitre.org/data/definitions/798.html"},
		},
		{
			id: "IAC-223", severity: findings.SeverityCritical, confidence: findings.ConfidenceMedium,
			pattern:      `(?i)(?:secret_key|private_key)\s*:\s*['"][^{'"]+['"]`,
			description:  "Ansible hardcoded secret/private key",
			cwe:          "CWE-798",
			keywords:     []string{"secret_key", "private_key"},
			filePatterns: []string{"*.yml", "*.yaml"},
			tags:         []string{"iac", "ansible", "secrets"},
			remediation:  "Store secret and private keys in Ansible Vault or an external secrets manager. Use file-based secrets with proper permissions (0600) and reference them via vault-encrypted variables.",
			references:   []string{"https://cwe.mitre.org/data/definitions/798.html"},
		},
		{
			id: "IAC-224", severity: findings.SeverityMedium, confidence: findings.ConfidenceMedium,
			pattern:      `(?i)authorized_key:.*key:\s*['"]?ssh-(?:rsa|ed25519|ecdsa)`,
			description:  "Ansible hardcoded SSH authorized key",
			cwe:          "CWE-798",
			keywords:     []string{"authorized_key", "ssh"},
			filePatterns: []string{"*.yml", "*.yaml"},
			tags:         []string{"iac", "ansible", "secrets"},
			remediation:  "Store SSH public keys in variables or files managed by Ansible Vault. Use lookup plugins (e.g., lookup('file', '~/.ssh/id_ed25519.pub')) to load keys at runtime rather than embedding them.",
			references:   []string{"https://cwe.mitre.org/data/definitions/798.html"},
		},
		{
			id: "IAC-225", severity: findings.SeverityCritical, confidence: findings.ConfidenceMedium,
			pattern:      `(?i)password\s*:\s*['"][^{$'"]+['"]`,
			description:  "Ansible variable with hardcoded password",
			cwe:          "CWE-798",
			keywords:     []string{"password"},
			filePatterns: []string{"*.yml", "*.yaml"},
			tags:         []string{"iac", "ansible", "secrets"},
			remediation:  "Use Ansible Vault to encrypt passwords. Run 'ansible-vault encrypt_string' for inline encryption or store all passwords in a vault-encrypted vars file. Never commit plaintext passwords to version control.",
			references:   []string{"https://cwe.mitre.org/data/definitions/798.html", "https://docs.ansible.com/ansible/latest/vault_guide/index.html"},
		},

		// =================================================================
		// Miscellaneous (IAC-226 to IAC-230)
		// =================================================================
		{
			id: "IAC-226", severity: findings.SeverityLow, confidence: findings.ConfidenceLow,
			pattern:      `(?i)delegate_to:\s*localhost`,
			description:  "Ansible task delegated to localhost",
			cwe:          "CWE-693",
			keywords:     []string{"delegate_to", "localhost"},
			filePatterns: []string{"*.yml", "*.yaml"},
			tags:         []string{"iac", "ansible", "best-practice"},
			remediation:  "Verify that localhost delegation is intentional and necessary. Tasks delegated to localhost run on the Ansible controller which may have elevated privileges or access to sensitive resources.",
			references:   []string{"https://cwe.mitre.org/data/definitions/693.html"},
		},
		{
			id: "IAC-227", severity: findings.SeverityLow, confidence: findings.ConfidenceLow,
			pattern:      `(?i)local_action:`,
			description:  "Ansible task uses local_action (prefer delegate_to)",
			cwe:          "CWE-693",
			keywords:     []string{"local_action"},
			filePatterns: []string{"*.yml", "*.yaml"},
			tags:         []string{"iac", "ansible", "best-practice"},
			remediation:  "Replace local_action with delegate_to: localhost for clarity. The delegate_to syntax is more explicit and easier to review for security implications.",
			references:   []string{"https://cwe.mitre.org/data/definitions/693.html"},
		},
		{
			id: "IAC-228", severity: findings.SeverityLow, confidence: findings.ConfidenceHigh,
			pattern:      `(?i)when:\s*['"]?true['"]?`,
			description:  "Ansible task with always-true condition",
			cwe:          "CWE-693",
			keywords:     []string{"when"},
			filePatterns: []string{"*.yml", "*.yaml"},
			tags:         []string{"iac", "ansible", "best-practice"},
			remediation:  "Remove the when: true condition as it serves no purpose. If the task should always run, omit the when clause entirely. This may indicate a debugging leftover.",
			references:   []string{"https://cwe.mitre.org/data/definitions/693.html"},
		},
		{
			id: "IAC-229", severity: findings.SeverityLow, confidence: findings.ConfidenceLow,
			pattern:      `(?i)debug:\s*\n?\s*msg:`,
			description:  "Ansible debug module in playbook (remove for production)",
			cwe:          "CWE-200",
			keywords:     []string{"debug", "msg"},
			filePatterns: []string{"*.yml", "*.yaml"},
			tags:         []string{"iac", "ansible", "best-practice"},
			remediation:  "Remove debug tasks before deploying to production. Debug output can leak sensitive information such as variable contents, credentials, and system details into logs and console output.",
			references:   []string{"https://cwe.mitre.org/data/definitions/200.html"},
		},
		{
			id: "IAC-230", severity: findings.SeverityMedium, confidence: findings.ConfidenceLow,
			pattern:      `(?i)(?:community|ansible)\.general.*latest`,
			description:  "Ansible module using 'latest' package state",
			cwe:          "CWE-829",
			keywords:     []string{"community", "ansible", "general", "latest"},
			filePatterns: []string{"*.yml", "*.yaml"},
			tags:         []string{"iac", "ansible", "supply-chain"},
			remediation:  "Pin packages to specific versions instead of using state: latest. Using latest can introduce untested or vulnerable package versions during automated deployments.",
			references:   []string{"https://cwe.mitre.org/data/definitions/829.html"},
		},
	}

	out := make([]rules.Rule, len(defs))
	for i := range defs {
		out[i] = rules.Rule{
			ID:           defs[i].id,
			Version:      "1.0",
			Description:  defs[i].description,
			Severity:     defs[i].severity,
			Confidence:   defs[i].confidence,
			MatcherType:  "regex",
			Pattern:      defs[i].pattern,
			FilePatterns: defs[i].filePatterns,
			Keywords:     defs[i].keywords,
			Tags:         defs[i].tags,
			Metadata:     map[string]string{"cwe": defs[i].cwe},
			Remediation:  defs[i].remediation,
			References:   defs[i].references,
		}
	}
	return out
}
