package iac

import (
	"github.com/nox-hq/nox/core/findings"
	"github.com/nox-hq/nox/core/rules"
)

// builtinExpandedIaCRules returns expanded IaC security rules (IAC-266 to IAC-365).
// These cover Terraform state/backend, AWS resources, Kubernetes advanced,
// GitHub Actions, Azure, GCP, Docker advanced, CI/CD general, and misc IaC patterns.
func builtinExpandedIaCRules() []rules.Rule {
	tfFilePatterns := []string{"*.tf"}
	tfAllFilePatterns := []string{"*.tf", "*.tfvars"}
	k8sFilePatterns := []string{"*.yaml", "*.yml"}
	ghaFilePatterns := []string{".github/workflows/*.yml", ".github/workflows/*.yaml", "*.yml", "*.yaml"}
	dockerFilePatterns := []string{"Dockerfile", "Dockerfile.*", "*.dockerfile"}
	ciFilePatterns := []string{".gitlab-ci.yml", "*.yml", "*.yaml"}

	defs := []iacRule{
		// =================================================================
		// Terraform State & Backend (IAC-266 to IAC-272)
		// =================================================================
		{
			id: "IAC-266", severity: findings.SeverityMedium, confidence: findings.ConfidenceHigh,
			pattern:      `(?i)backend\s*['"]?local['"]?`,
			description:  "Terraform uses local state backend",
			cwe:          "CWE-693",
			keywords:     []string{"backend", "local"},
			filePatterns: tfFilePatterns,
			tags:         []string{"iac", "terraform", "state"},
			remediation:  "Use a remote backend (e.g., S3, GCS, Azure Blob) instead of local state. Local state does not support team collaboration, locking, or encrypted storage.",
			references:   []string{"https://cwe.mitre.org/data/definitions/693.html"},
		},
		{
			id: "IAC-267", severity: findings.SeverityMedium, confidence: findings.ConfidenceLow,
			pattern:      `(?i)backend\s*['"]?s3['"]?`,
			description:  "Terraform S3 backend (verify encryption)",
			cwe:          "CWE-311",
			keywords:     []string{"backend", "s3"},
			filePatterns: tfFilePatterns,
			tags:         []string{"iac", "terraform", "state"},
			remediation:  "Ensure the S3 backend has encrypt = true, uses a KMS key, and that the bucket has server-side encryption enabled with versioning and access logging.",
			references:   []string{"https://cwe.mitre.org/data/definitions/311.html"},
		},
		{
			id: "IAC-268", severity: findings.SeverityLow, confidence: findings.ConfidenceLow,
			pattern:      `(?i)terraform\s*\{`,
			description:  "Terraform block (verify required_version is set)",
			cwe:          "CWE-693",
			keywords:     []string{"terraform"},
			filePatterns: tfFilePatterns,
			tags:         []string{"iac", "terraform", "best-practice"},
			remediation:  "Set required_version in the terraform block to prevent accidental use of incompatible Terraform versions that may corrupt state or produce unexpected behavior.",
			references:   []string{"https://cwe.mitre.org/data/definitions/693.html"},
		},
		{
			id: "IAC-269", severity: findings.SeverityMedium, confidence: findings.ConfidenceMedium,
			pattern:      `(?i)sensitive\s*=\s*false`,
			description:  "Terraform output explicitly marked not sensitive",
			cwe:          "CWE-200",
			keywords:     []string{"sensitive", "false"},
			filePatterns: tfFilePatterns,
			tags:         []string{"iac", "terraform", "secrets"},
			remediation:  "Review whether this output contains sensitive data. Setting sensitive = false causes values to appear in plan output, logs, and state, potentially exposing secrets.",
			references:   []string{"https://cwe.mitre.org/data/definitions/200.html"},
		},
		{
			id: "IAC-270", severity: findings.SeverityMedium, confidence: findings.ConfidenceLow,
			pattern:      `(?i)output\s*['"](?:.*(?:password|secret|key|token))['"]\s*\{`,
			description:  "Terraform output with sensitive name (verify sensitive=true)",
			cwe:          "CWE-200",
			keywords:     []string{"output", "password", "secret"},
			filePatterns: tfFilePatterns,
			tags:         []string{"iac", "terraform", "secrets"},
			remediation:  "Add sensitive = true to outputs whose names suggest they contain secrets. Without this flag, values are displayed in CLI output and stored in plain text in state.",
			references:   []string{"https://cwe.mitre.org/data/definitions/200.html"},
		},
		{
			id: "IAC-271", severity: findings.SeverityCritical, confidence: findings.ConfidenceHigh,
			pattern:      `(?i)(?:access_key|secret_key)\s*=\s*['"]`,
			description:  "Terraform provider with hardcoded credentials",
			cwe:          "CWE-798",
			keywords:     []string{"access_key", "secret_key"},
			filePatterns: tfAllFilePatterns,
			tags:         []string{"iac", "terraform", "secrets"},
			remediation:  "Remove hardcoded credentials and use environment variables, IAM roles, or a secrets manager. Hardcoded keys in source control can be extracted and abused.",
			references:   []string{"https://cwe.mitre.org/data/definitions/798.html"},
		},
		{
			id: "IAC-272", severity: findings.SeverityLow, confidence: findings.ConfidenceLow,
			pattern:      `(?i)default\s*=\s*['"][^'"]{8,}['"]`,
			description:  "Terraform variable with non-empty default (verify not secret)",
			cwe:          "CWE-798",
			keywords:     []string{"default"},
			filePatterns: tfFilePatterns,
			tags:         []string{"iac", "terraform", "best-practice"},
			remediation:  "Verify that variables with long default values do not contain secrets. Sensitive variables should have no default and should be supplied via environment variables or a tfvars file.",
			references:   []string{"https://cwe.mitre.org/data/definitions/798.html"},
		},

		// =================================================================
		// AWS Resources (IAC-273 to IAC-285)
		// =================================================================
		{
			id: "IAC-273", severity: findings.SeverityHigh, confidence: findings.ConfidenceHigh,
			pattern:      `(?i)http_tokens\s*=\s*['"]?optional`,
			description:  "EC2 instance without IMDSv2 enforcement",
			cwe:          "CWE-918",
			keywords:     []string{"http_tokens", "optional"},
			filePatterns: tfFilePatterns,
			tags:         []string{"iac", "terraform", "aws", "network"},
			remediation:  "Set http_tokens = \"required\" to enforce IMDSv2. IMDSv1 is vulnerable to SSRF attacks that can steal instance credentials from the metadata service.",
			references:   []string{"https://cwe.mitre.org/data/definitions/918.html"},
		},
		{
			id: "IAC-274", severity: findings.SeverityHigh, confidence: findings.ConfidenceHigh,
			pattern:      `(?i)guardduty.*enable\s*=\s*false`,
			description:  "AWS GuardDuty detector disabled",
			cwe:          "CWE-693",
			keywords:     []string{"guardduty", "enable"},
			filePatterns: tfFilePatterns,
			tags:         []string{"iac", "terraform", "aws", "monitoring"},
			remediation:  "Enable GuardDuty to detect threats such as compromised instances, reconnaissance, and credential exfiltration. Disabling it leaves the account without continuous threat detection.",
			references:   []string{"https://cwe.mitre.org/data/definitions/693.html"},
		},
		{
			id: "IAC-275", severity: findings.SeverityLow, confidence: findings.ConfidenceLow,
			pattern:      `(?i)resource\s*['"]aws_vpc['"]`,
			description:  "AWS VPC (verify VPC flow logs are enabled)",
			cwe:          "CWE-778",
			keywords:     []string{"aws_vpc"},
			filePatterns: tfFilePatterns,
			tags:         []string{"iac", "terraform", "aws", "logging"},
			remediation:  "Enable VPC Flow Logs to capture IP traffic information for network monitoring, troubleshooting, and forensic analysis of security incidents.",
			references:   []string{"https://cwe.mitre.org/data/definitions/778.html"},
		},
		{
			id: "IAC-276", severity: findings.SeverityMedium, confidence: findings.ConfidenceLow,
			pattern:      `(?i)resource\s*['"]aws_ebs_volume['"]`,
			description:  "AWS EBS volume (verify encryption is enabled)",
			cwe:          "CWE-311",
			keywords:     []string{"aws_ebs_volume"},
			filePatterns: tfFilePatterns,
			tags:         []string{"iac", "terraform", "aws", "encryption"},
			remediation:  "Enable encryption on EBS volumes with encrypted = true and specify a KMS key. Unencrypted volumes expose data at rest to unauthorized access if the underlying storage is compromised.",
			references:   []string{"https://cwe.mitre.org/data/definitions/311.html"},
		},
		{
			id: "IAC-277", severity: findings.SeverityMedium, confidence: findings.ConfidenceLow,
			pattern:      `(?i)resource\s*['"]aws_lambda_function['"]`,
			description:  "Lambda function (verify env variable encryption)",
			cwe:          "CWE-311",
			keywords:     []string{"aws_lambda_function"},
			filePatterns: tfFilePatterns,
			tags:         []string{"iac", "terraform", "aws", "encryption"},
			remediation:  "Specify kms_key_arn in the Lambda function to encrypt environment variables at rest. Without a customer-managed key, environment variables are encrypted with the default AWS key only.",
			references:   []string{"https://cwe.mitre.org/data/definitions/311.html"},
		},
		{
			id: "IAC-278", severity: findings.SeverityLow, confidence: findings.ConfidenceLow,
			pattern:      `(?i)resource\s*['"]aws_s3_bucket_versioning['"]`,
			description:  "S3 bucket versioning (verify enabled)",
			cwe:          "CWE-693",
			keywords:     []string{"aws_s3_bucket_versioning"},
			filePatterns: tfFilePatterns,
			tags:         []string{"iac", "terraform", "aws", "best-practice"},
			remediation:  "Enable versioning on S3 buckets to protect against accidental deletions and overwrites. Versioning allows recovery of previous object versions.",
			references:   []string{"https://cwe.mitre.org/data/definitions/693.html"},
		},
		{
			id: "IAC-279", severity: findings.SeverityLow, confidence: findings.ConfidenceLow,
			pattern:      `(?i)resource\s*['"]aws_dynamodb_table['"]`,
			description:  "DynamoDB table (verify point-in-time recovery)",
			cwe:          "CWE-693",
			keywords:     []string{"aws_dynamodb_table"},
			filePatterns: tfFilePatterns,
			tags:         []string{"iac", "terraform", "aws", "backup"},
			remediation:  "Enable point-in-time recovery on DynamoDB tables to allow continuous backups and restoration to any second within the retention window.",
			references:   []string{"https://cwe.mitre.org/data/definitions/693.html"},
		},
		{
			id: "IAC-280", severity: findings.SeverityMedium, confidence: findings.ConfidenceHigh,
			pattern:      `(?i)deletion_protection\s*=\s*false`,
			description:  "Terraform resource with deletion protection disabled",
			cwe:          "CWE-693",
			keywords:     []string{"deletion_protection", "false"},
			filePatterns: tfFilePatterns,
			tags:         []string{"iac", "terraform", "best-practice"},
			remediation:  "Enable deletion protection for critical resources such as databases and load balancers. Accidental deletion of production resources can cause significant outages and data loss.",
			references:   []string{"https://cwe.mitre.org/data/definitions/693.html"},
		},
		{
			id: "IAC-281", severity: findings.SeverityMedium, confidence: findings.ConfidenceHigh,
			pattern:      `(?i)force_destroy\s*=\s*true`,
			description:  "Terraform resource with force_destroy enabled",
			cwe:          "CWE-693",
			keywords:     []string{"force_destroy", "true"},
			filePatterns: tfFilePatterns,
			tags:         []string{"iac", "terraform", "destructive"},
			remediation:  "Avoid force_destroy = true on production resources. This allows Terraform to delete non-empty S3 buckets and other resources without confirmation, risking permanent data loss.",
			references:   []string{"https://cwe.mitre.org/data/definitions/693.html"},
		},
		{
			id: "IAC-282", severity: findings.SeverityMedium, confidence: findings.ConfidenceHigh,
			pattern:      `(?i)skip_final_snapshot\s*=\s*true`,
			description:  "Terraform RDS skips final snapshot on destroy",
			cwe:          "CWE-693",
			keywords:     []string{"skip_final_snapshot"},
			filePatterns: tfFilePatterns,
			tags:         []string{"iac", "terraform", "backup"},
			remediation:  "Set skip_final_snapshot = false and provide a final_snapshot_identifier. Without a final snapshot, all data is permanently lost when the RDS instance is destroyed.",
			references:   []string{"https://cwe.mitre.org/data/definitions/693.html"},
		},
		{
			id: "IAC-283", severity: findings.SeverityHigh, confidence: findings.ConfidenceHigh,
			pattern:      `(?i)publicly_accessible\s*=\s*true`,
			description:  "Terraform resource is publicly accessible",
			cwe:          "CWE-284",
			keywords:     []string{"publicly_accessible", "true"},
			filePatterns: tfFilePatterns,
			tags:         []string{"iac", "terraform", "network"},
			remediation:  "Set publicly_accessible = false and access the resource through a VPN, bastion host, or VPC endpoint. Public-facing databases and caches are common attack targets.",
			references:   []string{"https://cwe.mitre.org/data/definitions/284.html"},
		},
		{
			id: "IAC-284", severity: findings.SeverityMedium, confidence: findings.ConfidenceHigh,
			pattern:      `(?i)enable_key_rotation\s*=\s*false`,
			description:  "KMS key rotation disabled",
			cwe:          "CWE-320",
			keywords:     []string{"enable_key_rotation", "false"},
			filePatterns: tfFilePatterns,
			tags:         []string{"iac", "terraform", "encryption"},
			remediation:  "Enable automatic key rotation with enable_key_rotation = true. Regular key rotation limits the amount of data encrypted under a single key version, reducing blast radius if a key is compromised.",
			references:   []string{"https://cwe.mitre.org/data/definitions/320.html"},
		},
		{
			id: "IAC-285", severity: findings.SeverityMedium, confidence: findings.ConfidenceHigh,
			pattern:      `(?i)multi_az\s*=\s*false`,
			description:  "RDS instance without Multi-AZ",
			cwe:          "CWE-693",
			keywords:     []string{"multi_az", "false"},
			filePatterns: tfFilePatterns,
			tags:         []string{"iac", "terraform", "availability"},
			remediation:  "Enable Multi-AZ for production RDS instances to provide automatic failover to a standby replica in another Availability Zone during infrastructure failures.",
			references:   []string{"https://cwe.mitre.org/data/definitions/693.html"},
		},

		// =================================================================
		// Kubernetes Advanced (IAC-286 to IAC-305)
		// =================================================================
		{
			id: "IAC-286", severity: findings.SeverityLow, confidence: findings.ConfidenceLow,
			pattern:      `(?i)kind:\s*(?:Deployment|StatefulSet|DaemonSet)`,
			description:  "K8s workload (verify NetworkPolicy exists)",
			cwe:          "CWE-693",
			keywords:     []string{"Deployment", "StatefulSet", "DaemonSet"},
			filePatterns: k8sFilePatterns,
			tags:         []string{"iac", "kubernetes", "network"},
			remediation:  "Define NetworkPolicy resources to restrict ingress and egress traffic for workloads. Without NetworkPolicies, pods can communicate with any other pod in the cluster.",
			references:   []string{"https://cwe.mitre.org/data/definitions/693.html"},
		},
		{
			id: "IAC-287", severity: findings.SeverityMedium, confidence: findings.ConfidenceHigh,
			pattern:      `(?i)automountServiceAccountToken:\s*true`,
			description:  "K8s pod automounts service account token",
			cwe:          "CWE-284",
			keywords:     []string{"automountServiceAccountToken"},
			filePatterns: k8sFilePatterns,
			tags:         []string{"iac", "kubernetes", "privilege"},
			remediation:  "Set automountServiceAccountToken: false unless the pod needs to access the Kubernetes API. Mounted tokens can be exploited if the pod is compromised.",
			references:   []string{"https://cwe.mitre.org/data/definitions/284.html"},
		},
		{
			id: "IAC-288", severity: findings.SeverityCritical, confidence: findings.ConfidenceHigh,
			pattern:      `(?i)roleRef:(?:.*\n){0,3}.*name:\s*['"]?cluster-admin`,
			description:  "K8s ClusterRoleBinding to cluster-admin",
			cwe:          "CWE-250",
			keywords:     []string{"cluster-admin", "ClusterRoleBinding"},
			filePatterns: k8sFilePatterns,
			tags:         []string{"iac", "kubernetes", "privilege"},
			remediation:  "Avoid binding to the cluster-admin ClusterRole. Create a custom ClusterRole with only the specific permissions required, following the principle of least privilege.",
			references:   []string{"https://cwe.mitre.org/data/definitions/250.html"},
		},
		{
			id: "IAC-289", severity: findings.SeverityHigh, confidence: findings.ConfidenceHigh,
			pattern:      `(?i)apiGroups:\s*\[?\s*['"]?\*['"]?\s*\]?`,
			description:  "K8s RBAC with wildcard API group",
			cwe:          "CWE-250",
			keywords:     []string{"apiGroups", "*"},
			filePatterns: k8sFilePatterns,
			tags:         []string{"iac", "kubernetes", "privilege"},
			remediation:  "Replace wildcard API group with specific API groups. Wildcard access grants permissions across all current and future API groups, violating least privilege.",
			references:   []string{"https://cwe.mitre.org/data/definitions/250.html"},
		},
		{
			id: "IAC-290", severity: findings.SeverityHigh, confidence: findings.ConfidenceHigh,
			pattern:      `(?i)verbs:\s*\[?\s*['"]?\*['"]?\s*\]?`,
			description:  "K8s RBAC with wildcard verbs",
			cwe:          "CWE-250",
			keywords:     []string{"verbs", "*"},
			filePatterns: k8sFilePatterns,
			tags:         []string{"iac", "kubernetes", "privilege"},
			remediation:  "Replace wildcard verbs with specific verbs (get, list, watch, create, update, delete). Wildcard verbs grant all operations including escalate and impersonate.",
			references:   []string{"https://cwe.mitre.org/data/definitions/250.html"},
		},
		{
			id: "IAC-291", severity: findings.SeverityHigh, confidence: findings.ConfidenceHigh,
			pattern:      `(?i)hostPID:\s*true`,
			description:  "K8s pod uses host PID namespace",
			cwe:          "CWE-250",
			keywords:     []string{"hostPID"},
			filePatterns: k8sFilePatterns,
			tags:         []string{"iac", "kubernetes", "privilege"},
			remediation:  "Remove hostPID: true unless absolutely required. Sharing the host PID namespace allows the container to see and signal all host processes, enabling privilege escalation.",
			references:   []string{"https://cwe.mitre.org/data/definitions/250.html"},
		},
		{
			id: "IAC-292", severity: findings.SeverityHigh, confidence: findings.ConfidenceHigh,
			pattern:      `(?i)hostIPC:\s*true`,
			description:  "K8s pod uses host IPC namespace",
			cwe:          "CWE-250",
			keywords:     []string{"hostIPC"},
			filePatterns: k8sFilePatterns,
			tags:         []string{"iac", "kubernetes", "privilege"},
			remediation:  "Remove hostIPC: true. Sharing the host IPC namespace allows the container to access shared memory segments on the host, which can be exploited for data exfiltration.",
			references:   []string{"https://cwe.mitre.org/data/definitions/250.html"},
		},
		{
			id: "IAC-293", severity: findings.SeverityHigh, confidence: findings.ConfidenceMedium,
			pattern:      `(?i)hostPath:\s*\n\s*path:\s*['"]?/`,
			description:  "K8s pod mounts host filesystem path",
			cwe:          "CWE-250",
			keywords:     []string{"hostPath"},
			filePatterns: k8sFilePatterns,
			tags:         []string{"iac", "kubernetes", "privilege"},
			remediation:  "Avoid hostPath volumes. Use PersistentVolumeClaims or projected volumes instead. HostPath mounts give direct access to the node filesystem, enabling container breakout.",
			references:   []string{"https://cwe.mitre.org/data/definitions/250.html"},
		},
		{
			id: "IAC-294", severity: findings.SeverityMedium, confidence: findings.ConfidenceLow,
			pattern:      `(?i)emptyDir:\s*\{?\s*\}?`,
			description:  "K8s emptyDir volume without sizeLimit",
			cwe:          "CWE-770",
			keywords:     []string{"emptyDir"},
			filePatterns: k8sFilePatterns,
			tags:         []string{"iac", "kubernetes", "resource-management"},
			remediation:  "Set a sizeLimit on emptyDir volumes to prevent a container from consuming all available disk space on the node, which could cause node-level failures.",
			references:   []string{"https://cwe.mitre.org/data/definitions/770.html"},
		},
		{
			id: "IAC-295", severity: findings.SeverityMedium, confidence: findings.ConfidenceHigh,
			pattern:      `(?i)imagePullPolicy:\s*['"]?Never`,
			description:  "K8s imagePullPolicy set to Never",
			cwe:          "CWE-829",
			keywords:     []string{"imagePullPolicy", "Never"},
			filePatterns: k8sFilePatterns,
			tags:         []string{"iac", "kubernetes", "supply-chain"},
			remediation:  "Avoid imagePullPolicy: Never in production. This policy requires images to already exist on the node and prevents pulling updated or patched images.",
			references:   []string{"https://cwe.mitre.org/data/definitions/829.html"},
		},
		{
			id: "IAC-296", severity: findings.SeverityMedium, confidence: findings.ConfidenceLow,
			pattern:      `(?i)kind:\s*Ingress`,
			description:  "K8s Ingress (verify TLS termination)",
			cwe:          "CWE-319",
			keywords:     []string{"Ingress"},
			filePatterns: k8sFilePatterns,
			tags:         []string{"iac", "kubernetes", "transport-security"},
			remediation:  "Ensure the Ingress resource defines a tls section with valid certificates. Without TLS termination, traffic between clients and the cluster is transmitted in plain text.",
			references:   []string{"https://cwe.mitre.org/data/definitions/319.html"},
		},
		{
			id: "IAC-297", severity: findings.SeverityHigh, confidence: findings.ConfidenceHigh,
			pattern:      `(?i)loadBalancerSourceRanges:\s*\n\s*-\s*['"]?0\.0\.0\.0/0`,
			description:  "K8s LoadBalancer open to all IPs",
			cwe:          "CWE-284",
			keywords:     []string{"loadBalancerSourceRanges", "0.0.0.0"},
			filePatterns: k8sFilePatterns,
			tags:         []string{"iac", "kubernetes", "network"},
			remediation:  "Restrict loadBalancerSourceRanges to specific trusted CIDR blocks. Allowing 0.0.0.0/0 exposes the service to the entire internet.",
			references:   []string{"https://cwe.mitre.org/data/definitions/284.html"},
		},
		{
			id: "IAC-298", severity: findings.SeverityLow, confidence: findings.ConfidenceHigh,
			pattern:      `(?i)externalTrafficPolicy:\s*['"]?Cluster`,
			description:  "K8s service externalTrafficPolicy Cluster (masks client IP)",
			cwe:          "CWE-693",
			keywords:     []string{"externalTrafficPolicy"},
			filePatterns: k8sFilePatterns,
			tags:         []string{"iac", "kubernetes", "network"},
			remediation:  "Consider using externalTrafficPolicy: Local to preserve client source IP addresses. The Cluster policy performs SNAT, making audit logging and IP-based access control unreliable.",
			references:   []string{"https://cwe.mitre.org/data/definitions/693.html"},
		},
		{
			id: "IAC-299", severity: findings.SeverityMedium, confidence: findings.ConfidenceMedium,
			pattern:      `(?i)type:\s*['"]?NodePort`,
			description:  "K8s service uses NodePort (verify firewall rules)",
			cwe:          "CWE-284",
			keywords:     []string{"NodePort"},
			filePatterns: k8sFilePatterns,
			tags:         []string{"iac", "kubernetes", "network"},
			remediation:  "Verify that firewall rules restrict access to the NodePort range (30000-32767). NodePort services are accessible on every cluster node, increasing the attack surface.",
			references:   []string{"https://cwe.mitre.org/data/definitions/284.html"},
		},
		{
			id: "IAC-300", severity: findings.SeverityHigh, confidence: findings.ConfidenceHigh,
			pattern:      `(?i)type:\s*['"]?Unconfined`,
			description:  "K8s pod with Unconfined seccomp profile",
			cwe:          "CWE-250",
			keywords:     []string{"seccompProfile", "Unconfined"},
			filePatterns: k8sFilePatterns,
			tags:         []string{"iac", "kubernetes", "privilege"},
			remediation:  "Use RuntimeDefault or a custom seccomp profile instead of Unconfined. The Unconfined profile disables syscall filtering, allowing containers to invoke any kernel syscall.",
			references:   []string{"https://cwe.mitre.org/data/definitions/250.html"},
		},
		{
			id: "IAC-301", severity: findings.SeverityHigh, confidence: findings.ConfidenceMedium,
			pattern:      `(?i)apparmor\.security.*:\s*['"]?unconfined`,
			description:  "K8s pod with unconfined AppArmor profile",
			cwe:          "CWE-250",
			keywords:     []string{"apparmor", "unconfined"},
			filePatterns: k8sFilePatterns,
			tags:         []string{"iac", "kubernetes", "privilege"},
			remediation:  "Use the runtime/default AppArmor profile or a custom profile instead of unconfined. Disabling AppArmor removes mandatory access control protections from the container.",
			references:   []string{"https://cwe.mitre.org/data/definitions/250.html"},
		},
		{
			id: "IAC-302", severity: findings.SeverityCritical, confidence: findings.ConfidenceHigh,
			pattern:      `(?i)add:\s*\n\s*-\s*['"]?(?:SYS_ADMIN|ALL|NET_ADMIN)`,
			description:  "K8s container adds dangerous capability",
			cwe:          "CWE-250",
			keywords:     []string{"capabilities", "SYS_ADMIN", "ALL"},
			filePatterns: k8sFilePatterns,
			tags:         []string{"iac", "kubernetes", "privilege"},
			remediation:  "Remove SYS_ADMIN, ALL, and NET_ADMIN capabilities. These grant near-root-level host access. Add only the specific capabilities the workload requires and drop all others.",
			references:   []string{"https://cwe.mitre.org/data/definitions/250.html"},
		},
		{
			id: "IAC-303", severity: findings.SeverityLow, confidence: findings.ConfidenceHigh,
			pattern:      `(?i)terminationGracePeriodSeconds:\s*0`,
			description:  "K8s pod with zero grace period",
			cwe:          "CWE-693",
			keywords:     []string{"terminationGracePeriodSeconds"},
			filePatterns: k8sFilePatterns,
			tags:         []string{"iac", "kubernetes", "availability"},
			remediation:  "Set a non-zero terminationGracePeriodSeconds to allow the application to drain connections and complete in-flight requests before termination.",
			references:   []string{"https://cwe.mitre.org/data/definitions/693.html"},
		},
		{
			id: "IAC-304", severity: findings.SeverityMedium, confidence: findings.ConfidenceHigh,
			pattern:      `(?i)kind:\s*PodSecurityPolicy`,
			description:  "K8s uses deprecated PodSecurityPolicy",
			cwe:          "CWE-693",
			keywords:     []string{"PodSecurityPolicy"},
			filePatterns: k8sFilePatterns,
			tags:         []string{"iac", "kubernetes", "best-practice"},
			remediation:  "Migrate from PodSecurityPolicy to Pod Security Admission (PSA). PodSecurityPolicy was removed in Kubernetes v1.25 and is no longer enforced.",
			references:   []string{"https://cwe.mitre.org/data/definitions/693.html"},
		},
		{
			id: "IAC-305", severity: findings.SeverityHigh, confidence: findings.ConfidenceHigh,
			pattern:      `(?i)allowedUnsafeSysctls:`,
			description:  "K8s allows unsafe sysctls",
			cwe:          "CWE-250",
			keywords:     []string{"allowedUnsafeSysctls"},
			filePatterns: k8sFilePatterns,
			tags:         []string{"iac", "kubernetes", "privilege"},
			remediation:  "Remove allowedUnsafeSysctls or restrict to the minimum required set. Unsafe sysctls can affect other pods on the same node and destabilize the kernel.",
			references:   []string{"https://cwe.mitre.org/data/definitions/250.html"},
		},

		// =================================================================
		// GitHub Actions Expanded (IAC-306 to IAC-320)
		// =================================================================
		{
			id: "IAC-306", severity: findings.SeverityMedium, confidence: findings.ConfidenceHigh,
			pattern:      `(?i)id-token:\s*write`,
			description:  "GHA workflow requests OIDC token write",
			cwe:          "CWE-284",
			keywords:     []string{"id-token", "write"},
			filePatterns: ghaFilePatterns,
			tags:         []string{"iac", "github-actions", "privilege"},
			remediation:  "Verify that OIDC token write permission is required for this workflow. This permission allows the workflow to request tokens for cloud provider authentication.",
			references:   []string{"https://cwe.mitre.org/data/definitions/284.html"},
		},
		{
			id: "IAC-307", severity: findings.SeverityLow, confidence: findings.ConfidenceHigh,
			pattern:      `(?i)environment:\s*['"]?production`,
			description:  "GHA workflow targets production environment",
			cwe:          "CWE-693",
			keywords:     []string{"environment", "production"},
			filePatterns: ghaFilePatterns,
			tags:         []string{"iac", "github-actions", "deployment"},
			remediation:  "Ensure the production environment has required reviewers, branch protection rules, and deployment gates configured in the repository settings.",
			references:   []string{"https://cwe.mitre.org/data/definitions/693.html"},
		},
		{
			id: "IAC-308", severity: findings.SeverityLow, confidence: findings.ConfidenceHigh,
			pattern:      `(?i)workflow_dispatch:`,
			description:  "GHA manual workflow dispatch enabled",
			cwe:          "CWE-693",
			keywords:     []string{"workflow_dispatch"},
			filePatterns: ghaFilePatterns,
			tags:         []string{"iac", "github-actions", "trigger"},
			remediation:  "Verify that workflow_dispatch triggers are intended and that the workflow validates any user-supplied inputs to prevent injection attacks.",
			references:   []string{"https://cwe.mitre.org/data/definitions/693.html"},
		},
		{
			id: "IAC-309", severity: findings.SeverityLow, confidence: findings.ConfidenceHigh,
			pattern:      `(?i)cancel-in-progress:\s*true`,
			description:  "GHA cancels in-progress runs (verify intent)",
			cwe:          "CWE-693",
			keywords:     []string{"cancel-in-progress"},
			filePatterns: ghaFilePatterns,
			tags:         []string{"iac", "github-actions", "best-practice"},
			remediation:  "Ensure that cancelling in-progress runs is intentional. For deployment workflows, cancellation may leave infrastructure in a partially applied state.",
			references:   []string{"https://cwe.mitre.org/data/definitions/693.html"},
		},
		{
			id: "IAC-310", severity: findings.SeverityMedium, confidence: findings.ConfidenceHigh,
			pattern:      `(?i)continue-on-error:\s*true`,
			description:  "GHA step continues on error",
			cwe:          "CWE-755",
			keywords:     []string{"continue-on-error"},
			filePatterns: ghaFilePatterns,
			tags:         []string{"iac", "github-actions", "error-handling"},
			remediation:  "Remove continue-on-error: true unless the failure is intentionally non-blocking. Ignoring errors can mask security scan failures and broken tests.",
			references:   []string{"https://cwe.mitre.org/data/definitions/755.html"},
		},
		{
			id: "IAC-311", severity: findings.SeverityHigh, confidence: findings.ConfidenceHigh,
			pattern:      `(?i)ACTIONS_ALLOW_UNSECURE_COMMANDS`,
			description:  "GHA uses deprecated unsecure commands",
			cwe:          "CWE-78",
			keywords:     []string{"ACTIONS_ALLOW_UNSECURE_COMMANDS"},
			filePatterns: ghaFilePatterns,
			tags:         []string{"iac", "github-actions", "security"},
			remediation:  "Remove ACTIONS_ALLOW_UNSECURE_COMMANDS and migrate to the GITHUB_OUTPUT and GITHUB_ENV file-based alternatives. The old set-env and add-path commands are vulnerable to injection.",
			references:   []string{"https://cwe.mitre.org/data/definitions/78.html"},
		},
		{
			id: "IAC-312", severity: findings.SeverityMedium, confidence: findings.ConfidenceHigh,
			pattern:      `(?i)set-output\s+name=`,
			description:  "GHA uses deprecated set-output command",
			cwe:          "CWE-693",
			keywords:     []string{"set-output"},
			filePatterns: ghaFilePatterns,
			tags:         []string{"iac", "github-actions", "best-practice"},
			remediation:  "Replace ::set-output with the $GITHUB_OUTPUT file. The set-output command is deprecated and may be removed in a future runner version.",
			references:   []string{"https://cwe.mitre.org/data/definitions/693.html"},
		},
		{
			id: "IAC-313", severity: findings.SeverityMedium, confidence: findings.ConfidenceHigh,
			pattern:      `(?i)save-state\s+name=`,
			description:  "GHA uses deprecated save-state command",
			cwe:          "CWE-693",
			keywords:     []string{"save-state"},
			filePatterns: ghaFilePatterns,
			tags:         []string{"iac", "github-actions", "best-practice"},
			remediation:  "Replace ::save-state with the $GITHUB_STATE file. The save-state command is deprecated and may be removed in a future runner version.",
			references:   []string{"https://cwe.mitre.org/data/definitions/693.html"},
		},
		{
			id: "IAC-314", severity: findings.SeverityMedium, confidence: findings.ConfidenceMedium,
			pattern:      `(?i)contents:\s*write`,
			description:  "GHA workflow has contents write permission",
			cwe:          "CWE-284",
			keywords:     []string{"contents", "write"},
			filePatterns: ghaFilePatterns,
			tags:         []string{"iac", "github-actions", "privilege"},
			remediation:  "Verify that contents: write is required. This permission allows the workflow to push commits, create releases, and modify repository content.",
			references:   []string{"https://cwe.mitre.org/data/definitions/284.html"},
		},
		{
			id: "IAC-315", severity: findings.SeverityMedium, confidence: findings.ConfidenceMedium,
			pattern:      `(?i)packages:\s*write`,
			description:  "GHA workflow has packages write permission",
			cwe:          "CWE-284",
			keywords:     []string{"packages", "write"},
			filePatterns: ghaFilePatterns,
			tags:         []string{"iac", "github-actions", "privilege"},
			remediation:  "Verify that packages: write is required. This permission allows the workflow to publish packages to GitHub Packages, which could be exploited for supply chain attacks.",
			references:   []string{"https://cwe.mitre.org/data/definitions/284.html"},
		},
		{
			id: "IAC-316", severity: findings.SeverityMedium, confidence: findings.ConfidenceMedium,
			pattern:      `(?i)actions:\s*write`,
			description:  "GHA workflow has actions write permission",
			cwe:          "CWE-284",
			keywords:     []string{"actions", "write"},
			filePatterns: ghaFilePatterns,
			tags:         []string{"iac", "github-actions", "privilege"},
			remediation:  "Verify that actions: write is required. This permission allows the workflow to manage GitHub Actions, including modifying workflow files.",
			references:   []string{"https://cwe.mitre.org/data/definitions/284.html"},
		},
		{
			id: "IAC-317", severity: findings.SeverityCritical, confidence: findings.ConfidenceHigh,
			pattern:      `(?i)\$\{\{\s*github\.event\.(?:issue|comment|review|pull_request)\.body`,
			description:  "GHA uses event body in run (injection risk)",
			cwe:          "CWE-78",
			keywords:     []string{"github.event", "body"},
			filePatterns: ghaFilePatterns,
			tags:         []string{"iac", "github-actions", "injection"},
			remediation:  "Never use event body data directly in run steps. Assign the value to an environment variable first, which prevents shell injection from user-controlled content.",
			references:   []string{"https://cwe.mitre.org/data/definitions/78.html"},
		},
		{
			id: "IAC-318", severity: findings.SeverityHigh, confidence: findings.ConfidenceMedium,
			pattern:      `(?i)\$\{\{\s*github\.event\.(?:issue|pull_request)\.title`,
			description:  "GHA uses event title in context (injection risk)",
			cwe:          "CWE-78",
			keywords:     []string{"github.event", "title"},
			filePatterns: ghaFilePatterns,
			tags:         []string{"iac", "github-actions", "injection"},
			remediation:  "Avoid interpolating event titles directly into run steps. Use an intermediate environment variable to prevent shell command injection from user-controlled PR or issue titles.",
			references:   []string{"https://cwe.mitre.org/data/definitions/78.html"},
		},
		{
			id: "IAC-319", severity: findings.SeverityMedium, confidence: findings.ConfidenceHigh,
			pattern:      `(?i)runs-on:\s*['"]?self-hosted`,
			description:  "GHA workflow runs on self-hosted runner",
			cwe:          "CWE-693",
			keywords:     []string{"self-hosted"},
			filePatterns: ghaFilePatterns,
			tags:         []string{"iac", "github-actions", "infrastructure"},
			remediation:  "Ensure self-hosted runners are ephemeral, hardened, and network-isolated. Persistent runners can retain credentials, build artifacts, and malware between workflow runs.",
			references:   []string{"https://cwe.mitre.org/data/definitions/693.html"},
		},
		{
			id: "IAC-320", severity: findings.SeverityMedium, confidence: findings.ConfidenceMedium,
			pattern:      `(?i)uses:\s*docker://`,
			description:  "GHA step uses Docker container action",
			cwe:          "CWE-829",
			keywords:     []string{"docker://"},
			filePatterns: ghaFilePatterns,
			tags:         []string{"iac", "github-actions", "supply-chain"},
			remediation:  "Pin Docker container actions to a specific image digest (sha256) rather than a mutable tag. Unverified container images may contain malicious code.",
			references:   []string{"https://cwe.mitre.org/data/definitions/829.html"},
		},

		// =================================================================
		// Azure (IAC-321 to IAC-330)
		// =================================================================
		{
			id: "IAC-321", severity: findings.SeverityHigh, confidence: findings.ConfidenceHigh,
			pattern:      `(?i)enable_https_traffic_only\s*=\s*false`,
			description:  "Azure storage allows HTTP traffic",
			cwe:          "CWE-319",
			keywords:     []string{"enable_https_traffic_only"},
			filePatterns: tfFilePatterns,
			tags:         []string{"iac", "terraform", "azure", "transport-security"},
			remediation:  "Set enable_https_traffic_only = true to enforce HTTPS for all storage account traffic. HTTP traffic is unencrypted and vulnerable to interception.",
			references:   []string{"https://cwe.mitre.org/data/definitions/319.html"},
		},
		{
			id: "IAC-322", severity: findings.SeverityHigh, confidence: findings.ConfidenceHigh,
			pattern:      `(?i)min_tls_version\s*=\s*['"]?TLS1_0`,
			description:  "Azure resource with TLS 1.0",
			cwe:          "CWE-326",
			keywords:     []string{"min_tls_version", "TLS1_0"},
			filePatterns: tfFilePatterns,
			tags:         []string{"iac", "terraform", "azure", "transport-security"},
			remediation:  "Set min_tls_version to TLS1_2 or higher. TLS 1.0 has known vulnerabilities (BEAST, POODLE) and is deprecated by industry standards.",
			references:   []string{"https://cwe.mitre.org/data/definitions/326.html"},
		},
		{
			id: "IAC-323", severity: findings.SeverityHigh, confidence: findings.ConfidenceMedium,
			pattern:      `(?i)default_action\s*=\s*['"]?Allow`,
			description:  "Azure network default action allows all",
			cwe:          "CWE-284",
			keywords:     []string{"default_action", "Allow"},
			filePatterns: tfFilePatterns,
			tags:         []string{"iac", "terraform", "azure", "network"},
			remediation:  "Set default_action = \"Deny\" in network_rules and explicitly allow trusted IP ranges or virtual networks. A default allow policy exposes the resource to all networks.",
			references:   []string{"https://cwe.mitre.org/data/definitions/284.html"},
		},
		{
			id: "IAC-324", severity: findings.SeverityMedium, confidence: findings.ConfidenceHigh,
			pattern:      `(?i)admin_enabled\s*=\s*true`,
			description:  "Azure container registry admin account enabled",
			cwe:          "CWE-250",
			keywords:     []string{"admin_enabled"},
			filePatterns: tfFilePatterns,
			tags:         []string{"iac", "terraform", "azure", "privilege"},
			remediation:  "Disable the admin account and use Azure AD service principals or managed identities for container registry authentication. The admin account uses shared credentials.",
			references:   []string{"https://cwe.mitre.org/data/definitions/250.html"},
		},
		{
			id: "IAC-325", severity: findings.SeverityMedium, confidence: findings.ConfidenceLow,
			pattern:      `(?i)resource\s*['"]azurerm_virtual_machine['"]`,
			description:  "Azure VM (verify disk encryption)",
			cwe:          "CWE-311",
			keywords:     []string{"azurerm_virtual_machine"},
			filePatterns: tfFilePatterns,
			tags:         []string{"iac", "terraform", "azure", "encryption"},
			remediation:  "Enable Azure Disk Encryption or use disk_encryption_set_id to encrypt OS and data disks. Unencrypted disks expose data at rest if the underlying storage is accessed.",
			references:   []string{"https://cwe.mitre.org/data/definitions/311.html"},
		},
		{
			id: "IAC-326", severity: findings.SeverityMedium, confidence: findings.ConfidenceHigh,
			pattern:      `(?i)purge_protection_enabled\s*=\s*false`,
			description:  "Azure Key Vault without purge protection",
			cwe:          "CWE-693",
			keywords:     []string{"purge_protection_enabled"},
			filePatterns: tfFilePatterns,
			tags:         []string{"iac", "terraform", "azure", "best-practice"},
			remediation:  "Enable purge protection on Key Vault to prevent permanent deletion of secrets, keys, and certificates during the retention period.",
			references:   []string{"https://cwe.mitre.org/data/definitions/693.html"},
		},
		{
			id: "IAC-327", severity: findings.SeverityMedium, confidence: findings.ConfidenceMedium,
			pattern:      `(?i)soft_delete_retention_days\s*=\s*[0-7]\b`,
			description:  "Azure Key Vault with short soft delete retention",
			cwe:          "CWE-693",
			keywords:     []string{"soft_delete_retention_days"},
			filePatterns: tfFilePatterns,
			tags:         []string{"iac", "terraform", "azure", "best-practice"},
			remediation:  "Set soft_delete_retention_days to at least 7 days (recommended 90). Short retention periods reduce the window for recovering accidentally deleted secrets.",
			references:   []string{"https://cwe.mitre.org/data/definitions/693.html"},
		},
		{
			id: "IAC-328", severity: findings.SeverityMedium, confidence: findings.ConfidenceHigh,
			pattern:      `(?i)public_network_access_enabled\s*=\s*true`,
			description:  "Azure resource with public network access enabled",
			cwe:          "CWE-284",
			keywords:     []string{"public_network_access_enabled"},
			filePatterns: tfFilePatterns,
			tags:         []string{"iac", "terraform", "azure", "network"},
			remediation:  "Set public_network_access_enabled = false and use Private Endpoints for access. Public network access exposes the resource to potential internet-based attacks.",
			references:   []string{"https://cwe.mitre.org/data/definitions/284.html"},
		},
		{
			id: "IAC-329", severity: findings.SeverityMedium, confidence: findings.ConfidenceLow,
			pattern:      `(?i)resource\s*['"]azurerm_mssql_server['"]`,
			description:  "Azure SQL Server (verify network restrictions)",
			cwe:          "CWE-284",
			keywords:     []string{"azurerm_mssql_server"},
			filePatterns: tfFilePatterns,
			tags:         []string{"iac", "terraform", "azure", "network"},
			remediation:  "Disable public network access and use Private Endpoints or virtual network rules to restrict Azure SQL Server connectivity to trusted networks only.",
			references:   []string{"https://cwe.mitre.org/data/definitions/284.html"},
		},
		{
			id: "IAC-330", severity: findings.SeverityLow, confidence: findings.ConfidenceLow,
			pattern:      `(?i)resource\s*['"]azurerm_mssql_server_security_alert_policy['"]`,
			description:  "Azure SQL security alert policy (verify enabled)",
			cwe:          "CWE-693",
			keywords:     []string{"security_alert_policy"},
			filePatterns: tfFilePatterns,
			tags:         []string{"iac", "terraform", "azure", "monitoring"},
			remediation:  "Ensure the security alert policy state is set to Enabled. This provides alerts for anomalous database activities such as SQL injection and brute-force attacks.",
			references:   []string{"https://cwe.mitre.org/data/definitions/693.html"},
		},

		// =================================================================
		// GCP (IAC-331 to IAC-340)
		// =================================================================
		{
			id: "IAC-331", severity: findings.SeverityLow, confidence: findings.ConfidenceLow,
			pattern:      `(?i)resource\s*['"]google_compute_instance['"]`,
			description:  "GCP Compute Instance (verify shielded VM)",
			cwe:          "CWE-693",
			keywords:     []string{"google_compute_instance"},
			filePatterns: tfFilePatterns,
			tags:         []string{"iac", "terraform", "gcp", "best-practice"},
			remediation:  "Enable Shielded VM features (vTPM, integrity monitoring, secure boot) to protect against rootkits and bootkits on GCP Compute instances.",
			references:   []string{"https://cwe.mitre.org/data/definitions/693.html"},
		},
		{
			id: "IAC-332", severity: findings.SeverityMedium, confidence: findings.ConfidenceHigh,
			pattern:      `(?i)enable_integrity_monitoring\s*=\s*false`,
			description:  "GCP shielded VM integrity monitoring disabled",
			cwe:          "CWE-693",
			keywords:     []string{"enable_integrity_monitoring"},
			filePatterns: tfFilePatterns,
			tags:         []string{"iac", "terraform", "gcp", "monitoring"},
			remediation:  "Set enable_integrity_monitoring = true to detect unauthorized changes to the boot sequence and kernel. Disabling it removes a key defense against persistent malware.",
			references:   []string{"https://cwe.mitre.org/data/definitions/693.html"},
		},
		{
			id: "IAC-333", severity: findings.SeverityMedium, confidence: findings.ConfidenceHigh,
			pattern:      `(?i)enable_secure_boot\s*=\s*false`,
			description:  "GCP shielded VM secure boot disabled",
			cwe:          "CWE-693",
			keywords:     []string{"enable_secure_boot"},
			filePatterns: tfFilePatterns,
			tags:         []string{"iac", "terraform", "gcp", "security"},
			remediation:  "Set enable_secure_boot = true to ensure only verified boot software runs. Disabling secure boot allows unsigned or modified bootloaders and kernels.",
			references:   []string{"https://cwe.mitre.org/data/definitions/693.html"},
		},
		{
			id: "IAC-334", severity: findings.SeverityLow, confidence: findings.ConfidenceLow,
			pattern:      `(?i)resource\s*['"]google_storage_bucket['"]`,
			description:  "GCP storage bucket (verify uniform access)",
			cwe:          "CWE-693",
			keywords:     []string{"google_storage_bucket"},
			filePatterns: tfFilePatterns,
			tags:         []string{"iac", "terraform", "gcp", "best-practice"},
			remediation:  "Enable uniform bucket-level access to simplify permissions management. Object-level ACLs are harder to audit and can lead to unintended public exposure.",
			references:   []string{"https://cwe.mitre.org/data/definitions/693.html"},
		},
		{
			id: "IAC-335", severity: findings.SeverityMedium, confidence: findings.ConfidenceHigh,
			pattern:      `(?i)uniform_bucket_level_access\s*=\s*false`,
			description:  "GCP bucket without uniform access control",
			cwe:          "CWE-284",
			keywords:     []string{"uniform_bucket_level_access"},
			filePatterns: tfFilePatterns,
			tags:         []string{"iac", "terraform", "gcp", "privilege"},
			remediation:  "Set uniform_bucket_level_access = true. Without uniform access, both IAM and ACLs control access, making permissions difficult to audit and increasing the risk of misconfiguration.",
			references:   []string{"https://cwe.mitre.org/data/definitions/284.html"},
		},
		{
			id: "IAC-336", severity: findings.SeverityLow, confidence: findings.ConfidenceLow,
			pattern:      `(?i)resource\s*['"]google_sql_database_instance['"]`,
			description:  "GCP SQL instance (verify SSL enforcement)",
			cwe:          "CWE-693",
			keywords:     []string{"google_sql_database_instance"},
			filePatterns: tfFilePatterns,
			tags:         []string{"iac", "terraform", "gcp", "best-practice"},
			remediation:  "Enable require_ssl in the ip_configuration settings to enforce encrypted connections to the Cloud SQL instance. Unencrypted connections expose data in transit.",
			references:   []string{"https://cwe.mitre.org/data/definitions/693.html"},
		},
		{
			id: "IAC-337", severity: findings.SeverityHigh, confidence: findings.ConfidenceHigh,
			pattern:      `(?i)require_ssl\s*=\s*false`,
			description:  "GCP SQL instance without SSL enforcement",
			cwe:          "CWE-319",
			keywords:     []string{"require_ssl"},
			filePatterns: tfFilePatterns,
			tags:         []string{"iac", "terraform", "gcp", "transport-security"},
			remediation:  "Set require_ssl = true to enforce SSL/TLS connections to the Cloud SQL instance. Without SSL enforcement, database traffic is transmitted in plain text.",
			references:   []string{"https://cwe.mitre.org/data/definitions/319.html"},
		},
		{
			id: "IAC-338", severity: findings.SeverityCritical, confidence: findings.ConfidenceHigh,
			pattern:      `(?i)value\s*=\s*['"]?0\.0\.0\.0/0`,
			description:  "GCP SQL allows all IPs in authorized networks",
			cwe:          "CWE-284",
			keywords:     []string{"authorized_networks", "0.0.0.0"},
			filePatterns: tfFilePatterns,
			tags:         []string{"iac", "terraform", "gcp", "network"},
			remediation:  "Restrict authorized_networks to specific trusted IP ranges. Allowing 0.0.0.0/0 exposes the database to the entire internet, significantly increasing attack surface.",
			references:   []string{"https://cwe.mitre.org/data/definitions/284.html"},
		},
		{
			id: "IAC-339", severity: findings.SeverityLow, confidence: findings.ConfidenceLow,
			pattern:      `(?i)resource\s*['"]google_compute_subnetwork['"]`,
			description:  "GCP subnetwork (verify flow logs)",
			cwe:          "CWE-778",
			keywords:     []string{"google_compute_subnetwork"},
			filePatterns: tfFilePatterns,
			tags:         []string{"iac", "terraform", "gcp", "logging"},
			remediation:  "Enable VPC Flow Logs on the subnetwork for network monitoring and forensic analysis. Flow logs capture traffic metadata for detecting anomalous patterns.",
			references:   []string{"https://cwe.mitre.org/data/definitions/778.html"},
		},
		{
			id: "IAC-340", severity: findings.SeverityLow, confidence: findings.ConfidenceLow,
			pattern:      `(?i)resource\s*['"]google_container_cluster['"]`,
			description:  "GKE cluster (verify binary authorization)",
			cwe:          "CWE-693",
			keywords:     []string{"google_container_cluster"},
			filePatterns: tfFilePatterns,
			tags:         []string{"iac", "terraform", "gcp", "supply-chain"},
			remediation:  "Enable Binary Authorization on GKE clusters to enforce deploy-time attestation policies, ensuring only trusted and verified container images are deployed.",
			references:   []string{"https://cwe.mitre.org/data/definitions/693.html"},
		},

		// =================================================================
		// Docker Advanced (IAC-341 to IAC-345) [NOTE: IAC-346-350 are CI/CD]
		// =================================================================
		{
			id: "IAC-341", severity: findings.SeverityMedium, confidence: findings.ConfidenceHigh,
			pattern:      `(?im)^\s*HEALTHCHECK\s+NONE`,
			description:  "Dockerfile disables healthcheck",
			cwe:          "CWE-693",
			keywords:     []string{"HEALTHCHECK", "NONE"},
			filePatterns: dockerFilePatterns,
			tags:         []string{"iac", "docker", "availability"},
			remediation:  "Define a meaningful HEALTHCHECK instruction instead of NONE. Without health checks, orchestrators cannot detect and replace unhealthy containers.",
			references:   []string{"https://cwe.mitre.org/data/definitions/693.html"},
		},
		{
			id: "IAC-342", severity: findings.SeverityHigh, confidence: findings.ConfidenceHigh,
			pattern:      `(?im)^\s*EXPOSE\s+(?:22|3389|5900)\b`,
			description:  "Dockerfile exposes remote access port",
			cwe:          "CWE-284",
			keywords:     []string{"EXPOSE", "22", "3389"},
			filePatterns: dockerFilePatterns,
			tags:         []string{"iac", "docker", "network"},
			remediation:  "Do not expose remote access ports (SSH 22, RDP 3389, VNC 5900) in containers. Use kubectl exec, docker exec, or orchestrator-level access mechanisms instead.",
			references:   []string{"https://cwe.mitre.org/data/definitions/284.html"},
		},
		{
			id: "IAC-343", severity: findings.SeverityHigh, confidence: findings.ConfidenceHigh,
			pattern:      `(?im)^\s*ENV\s+(?:PASSWORD|SECRET|TOKEN|API_KEY)\s*=`,
			description:  "Dockerfile sets secret in ENV instruction",
			cwe:          "CWE-798",
			keywords:     []string{"ENV", "PASSWORD", "SECRET"},
			filePatterns: dockerFilePatterns,
			tags:         []string{"iac", "docker", "secrets"},
			remediation:  "Do not store secrets in Dockerfile ENV instructions. ENV values are baked into image layers and visible via docker inspect. Use runtime secrets or a secrets manager instead.",
			references:   []string{"https://cwe.mitre.org/data/definitions/798.html"},
		},
		{
			id: "IAC-344", severity: findings.SeverityCritical, confidence: findings.ConfidenceHigh,
			pattern:      `(?im)^\s*COPY\s+--from=\S+\s+/etc/shadow`,
			description:  "Dockerfile copies shadow file from build stage",
			cwe:          "CWE-538",
			keywords:     []string{"shadow"},
			filePatterns: dockerFilePatterns,
			tags:         []string{"iac", "docker", "secrets"},
			remediation:  "Never copy /etc/shadow from build stages. The shadow file contains password hashes and should never be included in container images.",
			references:   []string{"https://cwe.mitre.org/data/definitions/538.html"},
		},
		{
			id: "IAC-345", severity: findings.SeverityLow, confidence: findings.ConfidenceLow,
			pattern:      `(?im)^\s*RUN\s+.*apt-get\s+install\s+.*\*`,
			description:  "Dockerfile apt-get install using wildcard package names",
			cwe:          "CWE-693",
			keywords:     []string{"apt-get", "install"},
			filePatterns: dockerFilePatterns,
			tags:         []string{"iac", "docker", "best-practice"},
			remediation:  "Avoid wildcard package installation in Dockerfiles. Pin specific packages to minimize the image attack surface.",
			references:   []string{"https://cwe.mitre.org/data/definitions/693.html"},
		},

		// =================================================================
		// CI/CD General (IAC-346 to IAC-355)
		// =================================================================
		{
			id: "IAC-346", severity: findings.SeverityMedium, confidence: findings.ConfidenceHigh,
			pattern:      `(?i)image:\s*['"]?docker:\s*dind`,
			description:  "CI uses Docker-in-Docker (security implications)",
			cwe:          "CWE-250",
			keywords:     []string{"docker", "dind"},
			filePatterns: ciFilePatterns,
			tags:         []string{"iac", "ci-cd", "privilege"},
			remediation:  "Consider using Kaniko, Buildah, or Docker socket mounting instead of DinD. Docker-in-Docker requires privileged mode, which grants full host access to the container.",
			references:   []string{"https://cwe.mitre.org/data/definitions/250.html"},
		},
		{
			id: "IAC-347", severity: findings.SeverityLow, confidence: findings.ConfidenceHigh,
			pattern:      `(?i)allow_failure:\s*true`,
			description:  "GitLab CI job allows failure",
			cwe:          "CWE-755",
			keywords:     []string{"allow_failure"},
			filePatterns: ciFilePatterns,
			tags:         []string{"iac", "ci-cd", "error-handling"},
			remediation:  "Review jobs with allow_failure: true to ensure they are non-critical. Allowing security scanning or testing jobs to fail silently can mask vulnerabilities.",
			references:   []string{"https://cwe.mitre.org/data/definitions/755.html"},
		},
		{
			id: "IAC-348", severity: findings.SeverityLow, confidence: findings.ConfidenceMedium,
			pattern:      `(?i)when:\s*['"]?always['"]?`,
			description:  "CI job runs regardless of previous failures",
			cwe:          "CWE-693",
			keywords:     []string{"when", "always"},
			filePatterns: ciFilePatterns,
			tags:         []string{"iac", "ci-cd", "best-practice"},
			remediation:  "Verify that always-running jobs are intended for cleanup or notification purposes. Running deployment jobs after test failures can push broken code to production.",
			references:   []string{"https://cwe.mitre.org/data/definitions/693.html"},
		},
		{
			id: "IAC-349", severity: findings.SeverityLow, confidence: findings.ConfidenceLow,
			pattern:      `(?i)only:\s*\n\s*-\s*(?:tags|master|main)`,
			description:  "GitLab CI restricts to specific branches/tags only",
			cwe:          "CWE-693",
			keywords:     []string{"only"},
			filePatterns: ciFilePatterns,
			tags:         []string{"iac", "ci-cd", "deployment"},
			remediation:  "Migrate from 'only' to 'rules' syntax for more flexible and explicit CI job execution control. The 'only/except' keywords are less expressive and can cause unexpected behavior.",
			references:   []string{"https://cwe.mitre.org/data/definitions/693.html"},
		},
		{
			id: "IAC-350", severity: findings.SeverityMedium, confidence: findings.ConfidenceLow,
			pattern:      `(?i)untracked:\s*true`,
			description:  "CI caches untracked files (may include secrets)",
			cwe:          "CWE-200",
			keywords:     []string{"cache", "untracked"},
			filePatterns: ciFilePatterns,
			tags:         []string{"iac", "ci-cd", "secrets"},
			remediation:  "Avoid caching untracked files. Untracked files may include generated secrets, credentials, or sensitive build artifacts that should not persist between pipeline runs.",
			references:   []string{"https://cwe.mitre.org/data/definitions/200.html"},
		},
		{
			id: "IAC-351", severity: findings.SeverityCritical, confidence: findings.ConfidenceMedium,
			pattern:      `(?i)(?:PASSWORD|SECRET_KEY|TOKEN)\s*:\s*['"]?[A-Za-z0-9]`,
			description:  "CI variable with hardcoded secret",
			cwe:          "CWE-798",
			keywords:     []string{"PASSWORD", "SECRET", "TOKEN"},
			filePatterns: ciFilePatterns,
			tags:         []string{"iac", "ci-cd", "secrets"},
			remediation:  "Move hardcoded secrets to CI/CD protected variables or a secrets manager. Secrets in pipeline configuration files are stored in version control and accessible to all contributors.",
			references:   []string{"https://cwe.mitre.org/data/definitions/798.html"},
		},
		{
			id: "IAC-352", severity: findings.SeverityMedium, confidence: findings.ConfidenceMedium,
			pattern:      `(?i)expose_as:`,
			description:  "CI artifacts exposed publicly",
			cwe:          "CWE-200",
			keywords:     []string{"artifacts", "expose_as"},
			filePatterns: ciFilePatterns,
			tags:         []string{"iac", "ci-cd", "data-exposure"},
			remediation:  "Review exposed artifacts to ensure they do not contain sensitive information such as test credentials, internal URLs, or security scan reports.",
			references:   []string{"https://cwe.mitre.org/data/definitions/200.html"},
		},
		{
			id: "IAC-353", severity: findings.SeverityCritical, confidence: findings.ConfidenceHigh,
			pattern:      `(?i)script:\s*\n\s*-\s*curl.*\|\s*(?:bash|sh)`,
			description:  "CI script pipes curl to shell",
			cwe:          "CWE-829",
			keywords:     []string{"curl", "bash", "sh"},
			filePatterns: ciFilePatterns,
			tags:         []string{"iac", "ci-cd", "supply-chain"},
			remediation:  "Download scripts to a file, verify their checksum, then execute. Piping curl to shell executes arbitrary remote code without integrity verification.",
			references:   []string{"https://cwe.mitre.org/data/definitions/829.html"},
		},
		{
			id: "IAC-354", severity: findings.SeverityLow, confidence: findings.ConfidenceHigh,
			pattern:      `(?i)GIT_STRATEGY:\s*['"]?none`,
			description:  "CI disables git checkout strategy",
			cwe:          "CWE-693",
			keywords:     []string{"GIT_STRATEGY", "none"},
			filePatterns: ciFilePatterns,
			tags:         []string{"iac", "ci-cd", "best-practice"},
			remediation:  "Verify that disabling git checkout is intentional. Jobs without source code access may rely on cached or stale artifacts from previous pipelines.",
			references:   []string{"https://cwe.mitre.org/data/definitions/693.html"},
		},
		{
			id: "IAC-355", severity: findings.SeverityMedium, confidence: findings.ConfidenceMedium,
			pattern:      `(?i)services:\s*\n\s*-\s*\w+:latest`,
			description:  "CI service uses latest tag",
			cwe:          "CWE-829",
			keywords:     []string{"services", "latest"},
			filePatterns: ciFilePatterns,
			tags:         []string{"iac", "ci-cd", "supply-chain"},
			remediation:  "Pin CI service images to a specific version tag or digest. The 'latest' tag is mutable and can introduce breaking changes or vulnerabilities without notice.",
			references:   []string{"https://cwe.mitre.org/data/definitions/829.html"},
		},

		// =================================================================
		// Misc IaC (IAC-356 to IAC-365)
		// =================================================================
		{
			id: "IAC-356", severity: findings.SeverityMedium, confidence: findings.ConfidenceHigh,
			pattern:      `(?i)apiVersion:\s*['"]?v1['"]?\s*\nkind:\s*['"]?Secret`,
			description:  "K8s Secret in plain YAML (use sealed-secrets or external-secrets)",
			cwe:          "CWE-312",
			keywords:     []string{"kind", "Secret"},
			filePatterns: k8sFilePatterns,
			tags:         []string{"iac", "kubernetes", "secrets"},
			remediation:  "Use Sealed Secrets, External Secrets Operator, or SOPS to manage Kubernetes secrets. Plain Secret manifests store data as base64 (not encrypted) in version control.",
			references:   []string{"https://cwe.mitre.org/data/definitions/312.html"},
		},
		{
			id: "IAC-357", severity: findings.SeverityMedium, confidence: findings.ConfidenceMedium,
			pattern:      `(?i)type:\s*['"]?Opaque`,
			description:  "K8s Opaque secret (verify encryption at rest)",
			cwe:          "CWE-312",
			keywords:     []string{"Opaque"},
			filePatterns: k8sFilePatterns,
			tags:         []string{"iac", "kubernetes", "secrets"},
			remediation:  "Ensure encryption at rest is enabled in the cluster (EncryptionConfiguration). Opaque secrets are stored in etcd and are readable by anyone with etcd access.",
			references:   []string{"https://cwe.mitre.org/data/definitions/312.html"},
		},
		{
			id: "IAC-358", severity: findings.SeverityHigh, confidence: findings.ConfidenceHigh,
			pattern:      `(?i)stringData:`,
			description:  "K8s Secret with plaintext stringData",
			cwe:          "CWE-312",
			keywords:     []string{"stringData"},
			filePatterns: k8sFilePatterns,
			tags:         []string{"iac", "kubernetes", "secrets"},
			remediation:  "Avoid committing Secrets with stringData to version control. Use a secrets management solution (Sealed Secrets, External Secrets Operator, Vault) instead of plain manifests.",
			references:   []string{"https://cwe.mitre.org/data/definitions/312.html"},
		},
		{
			id: "IAC-359", severity: findings.SeverityMedium, confidence: findings.ConfidenceHigh,
			pattern:      `(?i)schedule:\s*['"]?\*\s+\*\s+\*\s+\*\s+\*`,
			description:  "K8s CronJob runs every minute",
			cwe:          "CWE-770",
			keywords:     []string{"schedule", "CronJob"},
			filePatterns: k8sFilePatterns,
			tags:         []string{"iac", "kubernetes", "resource-management"},
			remediation:  "Review the CronJob schedule. Running every minute can cause resource exhaustion and pod accumulation if jobs take longer than one minute to complete.",
			references:   []string{"https://cwe.mitre.org/data/definitions/770.html"},
		},
		{
			id: "IAC-360", severity: findings.SeverityLow, confidence: findings.ConfidenceHigh,
			pattern:      `(?i)restartPolicy:\s*['"]?Never`,
			description:  "K8s pod restart policy set to Never",
			cwe:          "CWE-693",
			keywords:     []string{"restartPolicy", "Never"},
			filePatterns: k8sFilePatterns,
			tags:         []string{"iac", "kubernetes", "availability"},
			remediation:  "Verify that restartPolicy: Never is intentional. Pods with this policy will not be restarted after failure, which may cause service outages for long-running workloads.",
			references:   []string{"https://cwe.mitre.org/data/definitions/693.html"},
		},
		{
			id: "IAC-361", severity: findings.SeverityMedium, confidence: findings.ConfidenceHigh,
			pattern:      `(?i)revisionHistoryLimit:\s*0`,
			description:  "K8s deployment with zero revision history",
			cwe:          "CWE-693",
			keywords:     []string{"revisionHistoryLimit"},
			filePatterns: k8sFilePatterns,
			tags:         []string{"iac", "kubernetes", "best-practice"},
			remediation:  "Set revisionHistoryLimit to at least 3. With zero history, rollback to a previous revision is impossible, making recovery from bad deployments significantly harder.",
			references:   []string{"https://cwe.mitre.org/data/definitions/693.html"},
		},
		{
			id: "IAC-362", severity: findings.SeverityLow, confidence: findings.ConfidenceMedium,
			pattern:      `(?i)minReadySeconds:\s*0`,
			description:  "K8s deployment with zero minReadySeconds",
			cwe:          "CWE-693",
			keywords:     []string{"minReadySeconds"},
			filePatterns: k8sFilePatterns,
			tags:         []string{"iac", "kubernetes", "availability"},
			remediation:  "Set a non-zero minReadySeconds value (e.g., 10-30 seconds) to ensure new pods are stable before marking them as available. This prevents cascading failures during rollouts.",
			references:   []string{"https://cwe.mitre.org/data/definitions/693.html"},
		},
		{
			id: "IAC-363", severity: findings.SeverityMedium, confidence: findings.ConfidenceHigh,
			pattern:      `(?i)strategy:\s*\n\s*type:\s*['"]?Recreate`,
			description:  "K8s deployment uses Recreate strategy (causes downtime)",
			cwe:          "CWE-693",
			keywords:     []string{"strategy", "Recreate"},
			filePatterns: k8sFilePatterns,
			tags:         []string{"iac", "kubernetes", "availability"},
			remediation:  "Use RollingUpdate strategy instead of Recreate for production workloads. The Recreate strategy terminates all existing pods before creating new ones, causing downtime.",
			references:   []string{"https://cwe.mitre.org/data/definitions/693.html"},
		},
		{
			id: "IAC-364", severity: findings.SeverityLow, confidence: findings.ConfidenceLow,
			pattern:      `(?i)topologySpreadConstraints:`,
			description:  "K8s topology spread constraints defined (positive)",
			cwe:          "CWE-693",
			keywords:     []string{"topologySpreadConstraints"},
			filePatterns: k8sFilePatterns,
			tags:         []string{"iac", "kubernetes", "availability"},
			remediation:  "Verify that topologySpreadConstraints are configured correctly with appropriate maxSkew and topologyKey values to ensure even pod distribution across failure domains.",
			references:   []string{"https://cwe.mitre.org/data/definitions/693.html"},
		},
		{
			id: "IAC-365", severity: findings.SeverityMedium, confidence: findings.ConfidenceMedium,
			pattern:      `(?i)priorityClassName:\s*['"]?system-`,
			description:  "K8s pod uses system priority class",
			cwe:          "CWE-250",
			keywords:     []string{"priorityClassName", "system"},
			filePatterns: k8sFilePatterns,
			tags:         []string{"iac", "kubernetes", "privilege"},
			remediation:  "Avoid using system-node-critical or system-cluster-critical priority classes for application workloads. These are reserved for critical system components and may preempt other pods.",
			references:   []string{"https://cwe.mitre.org/data/definitions/250.html"},
		},
	}

	out := make([]rules.Rule, len(defs))
	for i := range defs {
		out[i] = rules.Rule{
			ID:           defs[i].id,
			Version:      "1.0",
			Description:  defs[i].description,
			Severity:     defs[i].severity,
			Confidence:   defs[i].confidence,
			MatcherType:  "regex",
			Pattern:      defs[i].pattern,
			FilePatterns: defs[i].filePatterns,
			Keywords:     defs[i].keywords,
			Tags:         defs[i].tags,
			Metadata:     map[string]string{"cwe": defs[i].cwe},
			Remediation:  defs[i].remediation,
			References:   defs[i].references,
		}
	}
	return out
}
