package iac

import (
	"github.com/nox-hq/nox/core/findings"
	"github.com/nox-hq/nox/core/rules"
)

// iacRule is a compact representation used to define built-in IaC security rules
// in a table. Each entry is converted to a rules.Rule by builtinIaCRules().
type iacRule struct {
	id           string
	severity     findings.Severity
	confidence   findings.Confidence
	pattern      string
	description  string
	cwe          string
	keywords     []string
	filePatterns []string
	tags         []string
	remediation  string
	references   []string
}

// builtinIaCRules returns all built-in IaC security rules.
func builtinIaCRules() []rules.Rule {
	defs := []iacRule{
		// =================================================================
		// Dockerfile rules (IAC-001 to IAC-003, IAC-022 to IAC-025)
		// =================================================================
		{
			id: "IAC-001", severity: findings.SeverityHigh, confidence: findings.ConfidenceMedium,
			pattern:     `(?im)^\s*USER\s+root\s*$`,
			description: "Dockerfile runs as root user",
			cwe:         "CWE-250", keywords: []string{"user root"},
			filePatterns: []string{"Dockerfile", "Dockerfile.*", "*.dockerfile"},
			tags:         []string{"iac", "docker", "privilege"},
			remediation:  "Create a non-root user and switch to it with USER directive. Example: RUN adduser --disabled-password appuser && USER appuser.",
			references:   []string{"https://cwe.mitre.org/data/definitions/250.html", "https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#user"},
		},
		{
			id: "IAC-002", severity: findings.SeverityMedium, confidence: findings.ConfidenceMedium,
			pattern:     `(?im)^\s*FROM\s+[a-zA-Z0-9._/-]+\s*$|(?im)^\s*FROM\s+\S+:latest\b`,
			description: "Dockerfile uses unpinned base image (latest or no tag)",
			cwe:         "CWE-829", keywords: []string{"from"},
			filePatterns: []string{"Dockerfile", "Dockerfile.*", "*.dockerfile"},
			tags:         []string{"iac", "docker", "supply-chain"},
			remediation:  "Pin base images to a specific version and digest (e.g., 'node:20-alpine@sha256:abc...'). This ensures reproducible builds and protects against supply chain attacks.",
			references:   []string{"https://cwe.mitre.org/data/definitions/829.html"},
		},
		{
			id: "IAC-003", severity: findings.SeverityLow, confidence: findings.ConfidenceHigh,
			pattern:     `(?im)^\s*ADD\s+`,
			description: "Dockerfile uses ADD instead of COPY",
			cwe:         "CWE-829", keywords: []string{"add"},
			filePatterns: []string{"Dockerfile", "Dockerfile.*", "*.dockerfile"},
			tags:         []string{"iac", "docker", "best-practice"},
			remediation:  "Use COPY instead of ADD for local file copying. ADD has implicit tar extraction and remote URL support that can introduce unexpected behaviour.",
			references:   []string{"https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#add-or-copy"},
		},
		{
			id: "IAC-022", severity: findings.SeverityHigh, confidence: findings.ConfidenceMedium,
			pattern:     `(?im)^\s*ARG\s+(PASSWORD|SECRET|TOKEN|API_KEY|PRIVATE_KEY|DB_PASS|MYSQL_PASSWORD|POSTGRES_PASSWORD)\b`,
			description: "Secret value passed as Docker build argument",
			cwe:         "CWE-798", keywords: []string{"arg"},
			filePatterns: []string{"Dockerfile", "Dockerfile.*", "*.dockerfile"},
			tags:         []string{"iac", "docker", "secrets"},
			remediation:  "Use Docker BuildKit secrets (--mount=type=secret) instead of ARG for sensitive values. Build arguments are visible in image history and layer metadata.",
			references:   []string{"https://cwe.mitre.org/data/definitions/798.html", "https://docs.docker.com/build/building/secrets/"},
		},
		{
			id: "IAC-023", severity: findings.SeverityHigh, confidence: findings.ConfidenceHigh,
			pattern:     `(?i)curl\s+[^|]*\|\s*(sh|bash|zsh)|wget\s+[^|]*\|\s*(sh|bash|zsh)`,
			description: "Remote script piped directly to shell",
			cwe:         "CWE-94", keywords: []string{"curl", "wget"},
			filePatterns: []string{"Dockerfile", "Dockerfile.*", "*.dockerfile"},
			tags:         []string{"iac", "docker", "supply-chain"},
			remediation:  "Download scripts to a file first, verify their checksum, then execute. Piping from curl to shell skips integrity checks and risks executing tampered content.",
			references:   []string{"https://cwe.mitre.org/data/definitions/94.html"},
		},
		{
			id: "IAC-024", severity: findings.SeverityMedium, confidence: findings.ConfidenceMedium,
			pattern:     `(?im)^\s*RUN\s+.*\bsudo\b`,
			description: "Dockerfile RUN uses sudo (unnecessary in Docker build)",
			cwe:         "CWE-250", keywords: []string{"sudo"},
			filePatterns: []string{"Dockerfile", "Dockerfile.*", "*.dockerfile"},
			tags:         []string{"iac", "docker", "privilege"},
			remediation:  "Remove sudo from RUN commands. Docker builds run as root by default. Use USER to switch to a non-root user after installation steps.",
			references:   []string{"https://cwe.mitre.org/data/definitions/250.html"},
		},
		{
			id: "IAC-025", severity: findings.SeverityMedium, confidence: findings.ConfidenceHigh,
			pattern:     `(?im)^\s*(COPY|ADD)\s+--chmod=777\b`,
			description: "Dockerfile COPY/ADD sets world-writable permissions",
			cwe:         "CWE-732", keywords: []string{"chmod=777"},
			filePatterns: []string{"Dockerfile", "Dockerfile.*", "*.dockerfile"},
			tags:         []string{"iac", "docker", "permissions"},
			remediation:  "Use restrictive file permissions (e.g., --chmod=755 or --chmod=644). World-writable files allow any process in the container to modify them.",
			references:   []string{"https://cwe.mitre.org/data/definitions/732.html"},
		},

		// =================================================================
		// Terraform / Cloud rules (IAC-004 to IAC-006, IAC-036 to IAC-045)
		// =================================================================
		{
			id: "IAC-004", severity: findings.SeverityHigh, confidence: findings.ConfidenceMedium,
			pattern:     `(?i)(cidr_blocks|ingress_cidr|source_ranges)\s*=\s*\[?\s*"0\.0\.0\.0/0"`,
			description: "Terraform resource allows public access (0.0.0.0/0)",
			cwe:         "CWE-284", keywords: []string{"0.0.0.0/0"},
			filePatterns: []string{"*.tf", "*.tfvars"},
			tags:         []string{"iac", "terraform", "network"},
			remediation:  "Restrict CIDR blocks to specific IP ranges or VPC subnets instead of 0.0.0.0/0. Use security groups and NACLs for defense in depth.",
			references:   []string{"https://cwe.mitre.org/data/definitions/284.html"},
		},
		{
			id: "IAC-005", severity: findings.SeverityHigh, confidence: findings.ConfidenceLow,
			pattern:     `(?i)encrypt\w*\s*=\s*(false|"false")`,
			description: "Terraform resource has encryption disabled",
			cwe:         "CWE-311", keywords: []string{"encrypt"},
			filePatterns: []string{"*.tf", "*.tfvars"},
			tags:         []string{"iac", "terraform", "encryption"},
			remediation:  "Enable server-side encryption on all storage resources. Use aws_s3_bucket_server_side_encryption_configuration with AES-256 or AWS KMS.",
			references:   []string{"https://cwe.mitre.org/data/definitions/311.html", "https://docs.aws.amazon.com/AmazonS3/latest/userguide/bucket-encryption.html"},
		},
		{
			id: "IAC-006", severity: findings.SeverityCritical, confidence: findings.ConfidenceMedium,
			pattern:     `(?i)(from_port|to_port)\s*=\s*22`,
			description: "Terraform security group allows SSH access (port 22)",
			cwe:         "CWE-284", keywords: []string{"from_port", "to_port"},
			filePatterns: []string{"*.tf"},
			tags:         []string{"iac", "terraform", "network"},
			remediation:  "Restrict SSH access to specific CIDR blocks or use AWS Systems Manager Session Manager instead of direct SSH. Never combine port 22 with 0.0.0.0/0.",
			references:   []string{"https://cwe.mitre.org/data/definitions/284.html"},
		},
		{
			id: "IAC-036", severity: findings.SeverityCritical, confidence: findings.ConfidenceHigh,
			pattern:     `(?i)publicly_accessible\s*=\s*true`,
			description: "RDS or database instance is publicly accessible",
			cwe:         "CWE-284", keywords: []string{"publicly_accessible"},
			filePatterns: []string{"*.tf", "*.tfvars"},
			tags:         []string{"iac", "terraform", "database", "network"},
			remediation:  "Set publicly_accessible = false and access the database through a VPC, bastion host, or VPN. Public database instances are a common attack vector.",
			references:   []string{"https://cwe.mitre.org/data/definitions/284.html"},
		},
		{
			id: "IAC-037", severity: findings.SeverityHigh, confidence: findings.ConfidenceHigh,
			pattern:     `(?i)storage_encrypted\s*=\s*false`,
			description: "RDS storage encryption disabled",
			cwe:         "CWE-311", keywords: []string{"storage_encrypted"},
			filePatterns: []string{"*.tf", "*.tfvars"},
			tags:         []string{"iac", "terraform", "database", "encryption"},
			remediation:  "Set storage_encrypted = true on RDS instances. Enable encryption at rest to protect sensitive data from unauthorized access to underlying storage.",
			references:   []string{"https://cwe.mitre.org/data/definitions/311.html"},
		},
		{
			id: "IAC-038", severity: findings.SeverityHigh, confidence: findings.ConfidenceHigh,
			pattern:     `(?i)is_multi_region_trail\s*=\s*false`,
			description: "CloudTrail multi-region logging disabled",
			cwe:         "CWE-778", keywords: []string{"is_multi_region_trail"},
			filePatterns: []string{"*.tf"},
			tags:         []string{"iac", "terraform", "logging", "aws"},
			remediation:  "Set is_multi_region_trail = true to ensure CloudTrail captures API activity across all AWS regions. Single-region trails miss activity in other regions.",
			references:   []string{"https://cwe.mitre.org/data/definitions/778.html"},
		},
		{
			id: "IAC-039", severity: findings.SeverityCritical, confidence: findings.ConfidenceMedium,
			pattern:     `(?i)("Action"\s*:\s*\[?\s*"\*"\s*\]?|actions\s*=\s*\[\s*"\*"\s*\])`,
			description: "IAM policy with wildcard action (*)",
			cwe:         "CWE-269", keywords: []string{"action", "actions"},
			filePatterns: []string{"*.tf", "*.json"},
			tags:         []string{"iac", "terraform", "iam", "privilege"},
			remediation:  "Follow the principle of least privilege. Replace wildcard actions with specific API actions required for the workload (e.g., 's3:GetObject' instead of '*').",
			references:   []string{"https://cwe.mitre.org/data/definitions/269.html"},
		},
		{
			id: "IAC-040", severity: findings.SeverityCritical, confidence: findings.ConfidenceHigh,
			pattern:     `(?i)acl\s*=\s*["'](public-read|public-read-write)["']`,
			description: "S3 bucket with public ACL",
			cwe:         "CWE-284", keywords: []string{"public-read"},
			filePatterns: []string{"*.tf", "*.tfvars"},
			tags:         []string{"iac", "terraform", "s3", "network"},
			remediation:  "Use acl = 'private' and S3 Block Public Access settings. Grant access via IAM policies and pre-signed URLs instead of public ACLs.",
			references:   []string{"https://cwe.mitre.org/data/definitions/284.html"},
		},
		{
			id: "IAC-041", severity: findings.SeverityHigh, confidence: findings.ConfidenceMedium,
			pattern:     `(?i)protocol\s*=\s*["']HTTP["']`,
			description: "Load balancer listener uses HTTP instead of HTTPS",
			cwe:         "CWE-319", keywords: []string{"protocol"},
			filePatterns: []string{"*.tf"},
			tags:         []string{"iac", "terraform", "network", "encryption"},
			remediation:  "Use HTTPS (TLS) for all load balancer listeners. Configure an ACM certificate and redirect HTTP to HTTPS to protect data in transit.",
			references:   []string{"https://cwe.mitre.org/data/definitions/319.html"},
		},
		{
			id: "IAC-042", severity: findings.SeverityHigh, confidence: findings.ConfidenceHigh,
			pattern:     `(?i)enable_https_traffic_only\s*=\s*false`,
			description: "Azure storage account allows HTTP traffic",
			cwe:         "CWE-319", keywords: []string{"enable_https_traffic_only"},
			filePatterns: []string{"*.tf"},
			tags:         []string{"iac", "terraform", "azure", "encryption"},
			remediation:  "Set enable_https_traffic_only = true to enforce HTTPS on Azure storage accounts. HTTP traffic exposes data to eavesdropping and tampering.",
			references:   []string{"https://cwe.mitre.org/data/definitions/319.html"},
		},
		{
			id: "IAC-043", severity: findings.SeverityHigh, confidence: findings.ConfidenceMedium,
			pattern:     `(?i)protocol\s*=\s*["']all["']`,
			description: "Cloud firewall rule allows all protocols",
			cwe:         "CWE-284", keywords: []string{"protocol"},
			filePatterns: []string{"*.tf"},
			tags:         []string{"iac", "terraform", "network", "gcp"},
			remediation:  "Restrict firewall rules to specific protocols (tcp, udp) and ports. Allowing all protocols creates an overly permissive network configuration.",
			references:   []string{"https://cwe.mitre.org/data/definitions/284.html"},
		},
		{
			id: "IAC-044", severity: findings.SeverityMedium, confidence: findings.ConfidenceLow,
			pattern:     `(?i)default_vpc|aws_default_vpc|aws_default_subnet`,
			description: "Terraform resource uses default VPC",
			cwe:         "CWE-1188", keywords: []string{"default_vpc", "aws_default"},
			filePatterns: []string{"*.tf"},
			tags:         []string{"iac", "terraform", "network", "aws"},
			remediation:  "Create dedicated VPCs with proper subnet design instead of using default VPCs. Default VPCs have permissive security settings not suitable for production.",
			references:   []string{"https://cwe.mitre.org/data/definitions/1188.html"},
		},
		{
			id: "IAC-045", severity: findings.SeverityHigh, confidence: findings.ConfidenceMedium,
			pattern:     `(?i)log_status\s*=\s*["']disabled["']|logging_service\s*=\s*["']none["']`,
			description: "Cloud resource logging disabled",
			cwe:         "CWE-778", keywords: []string{"log_status", "logging_service"},
			filePatterns: []string{"*.tf"},
			tags:         []string{"iac", "terraform", "logging"},
			remediation:  "Enable logging on all cloud resources. Audit logs are essential for security monitoring, incident response, and compliance.",
			references:   []string{"https://cwe.mitre.org/data/definitions/778.html"},
		},

		// =================================================================
		// Kubernetes rules (IAC-007 to IAC-010, IAC-026 to IAC-035)
		// =================================================================
		{
			id: "IAC-007", severity: findings.SeverityCritical, confidence: findings.ConfidenceHigh,
			pattern:     `(?i)privileged\s*:\s*true`,
			description: "Kubernetes pod running as privileged",
			cwe:         "CWE-250", keywords: []string{"privileged"},
			filePatterns: []string{"*.yaml", "*.yml"},
			tags:         []string{"iac", "kubernetes", "privilege"},
			remediation:  "Set privileged: false in the pod security context. Use specific capabilities (add/drop) instead of full privilege. Apply Pod Security Standards.",
			references:   []string{"https://cwe.mitre.org/data/definitions/250.html", "https://kubernetes.io/docs/concepts/security/pod-security-standards/"},
		},
		{
			id: "IAC-008", severity: findings.SeverityHigh, confidence: findings.ConfidenceHigh,
			pattern:     `(?i)hostNetwork\s*:\s*true`,
			description: "Kubernetes pod uses host network",
			cwe:         "CWE-284", keywords: []string{"hostnetwork"},
			filePatterns: []string{"*.yaml", "*.yml"},
			tags:         []string{"iac", "kubernetes", "network"},
			remediation:  "Remove hostNetwork: true and use Kubernetes Services and NetworkPolicies for pod communication. Host networking bypasses network isolation.",
			references:   []string{"https://cwe.mitre.org/data/definitions/284.html", "https://kubernetes.io/docs/concepts/services-networking/network-policies/"},
		},
		{
			id: "IAC-009", severity: findings.SeverityCritical, confidence: findings.ConfidenceHigh,
			pattern:     `(?i)allowPrivilegeEscalation\s*:\s*true`,
			description: "Kubernetes pod allows privilege escalation",
			cwe:         "CWE-250", keywords: []string{"allowprivilegeescalation"},
			filePatterns: []string{"*.yaml", "*.yml"},
			tags:         []string{"iac", "kubernetes", "privilege"},
			remediation:  "Set allowPrivilegeEscalation: false in the container security context. This prevents child processes from gaining more privileges than the parent.",
			references:   []string{"https://cwe.mitre.org/data/definitions/250.html", "https://kubernetes.io/docs/concepts/security/pod-security-standards/"},
		},
		{
			id: "IAC-010", severity: findings.SeverityHigh, confidence: findings.ConfidenceHigh,
			pattern:     `(?im)runAsUser\s*:\s*0\s*$`,
			description: "Kubernetes pod running as root (runAsUser: 0)",
			cwe:         "CWE-250", keywords: []string{"runasuser"},
			filePatterns: []string{"*.yaml", "*.yml"},
			tags:         []string{"iac", "kubernetes", "privilege"},
			remediation:  "Set runAsUser to a non-zero UID (e.g., 1000) and runAsNonRoot: true in the pod security context. Build container images to run as non-root.",
			references:   []string{"https://cwe.mitre.org/data/definitions/250.html"},
		},
		{
			id: "IAC-026", severity: findings.SeverityHigh, confidence: findings.ConfidenceHigh,
			pattern:     `(?i)hostPID\s*:\s*true`,
			description: "Kubernetes pod uses host PID namespace",
			cwe:         "CWE-250", keywords: []string{"hostpid"},
			filePatterns: []string{"*.yaml", "*.yml"},
			tags:         []string{"iac", "kubernetes", "privilege"},
			remediation:  "Remove hostPID: true. Sharing the host PID namespace allows the container to see and signal all processes on the host, breaking process isolation.",
			references:   []string{"https://cwe.mitre.org/data/definitions/250.html"},
		},
		{
			id: "IAC-027", severity: findings.SeverityHigh, confidence: findings.ConfidenceHigh,
			pattern:     `(?i)hostIPC\s*:\s*true`,
			description: "Kubernetes pod uses host IPC namespace",
			cwe:         "CWE-250", keywords: []string{"hostipc"},
			filePatterns: []string{"*.yaml", "*.yml"},
			tags:         []string{"iac", "kubernetes", "privilege"},
			remediation:  "Remove hostIPC: true. Sharing the host IPC namespace allows containers to access shared memory and IPC resources of other host processes.",
			references:   []string{"https://cwe.mitre.org/data/definitions/250.html"},
		},
		{
			id: "IAC-028", severity: findings.SeverityHigh, confidence: findings.ConfidenceHigh,
			pattern:     `(?im)^\s*-\s*(SYS_ADMIN|SYS_PTRACE|NET_RAW|SYS_MODULE|DAC_OVERRIDE)\s*$`,
			description: "Container adds dangerous Linux capability",
			cwe:         "CWE-250", keywords: []string{"sys_admin", "sys_ptrace", "net_raw"},
			filePatterns: []string{"*.yaml", "*.yml"},
			tags:         []string{"iac", "kubernetes", "privilege", "capabilities"},
			remediation:  "Drop all capabilities and add only those specifically needed. Dangerous capabilities like SYS_ADMIN, NET_RAW, and SYS_PTRACE break container isolation.",
			references:   []string{"https://cwe.mitre.org/data/definitions/250.html", "https://kubernetes.io/docs/concepts/security/pod-security-standards/"},
		},
		{
			id: "IAC-029", severity: findings.SeverityMedium, confidence: findings.ConfidenceHigh,
			pattern:     `(?i)readOnlyRootFilesystem\s*:\s*false`,
			description: "Container root filesystem is writable",
			cwe:         "CWE-732", keywords: []string{"readonlyrootfilesystem"},
			filePatterns: []string{"*.yaml", "*.yml"},
			tags:         []string{"iac", "kubernetes", "filesystem"},
			remediation:  "Set readOnlyRootFilesystem: true and use emptyDir or tmpfs volumes for writable directories. This prevents attackers from modifying container binaries.",
			references:   []string{"https://cwe.mitre.org/data/definitions/732.html"},
		},
		{
			id: "IAC-030", severity: findings.SeverityMedium, confidence: findings.ConfidenceMedium,
			pattern:     `(?i)automountServiceAccountToken\s*:\s*true`,
			description: "Service account token automatically mounted",
			cwe:         "CWE-269", keywords: []string{"automountserviceaccounttoken"},
			filePatterns: []string{"*.yaml", "*.yml"},
			tags:         []string{"iac", "kubernetes", "privilege"},
			remediation:  "Set automountServiceAccountToken: false unless the pod requires Kubernetes API access. Mounted tokens can be used for lateral movement if the pod is compromised.",
			references:   []string{"https://cwe.mitre.org/data/definitions/269.html"},
		},
		{
			id: "IAC-031", severity: findings.SeverityMedium, confidence: findings.ConfidenceMedium,
			pattern:     `(?i)image\s*:\s*["']?[a-zA-Z0-9._/-]+:latest["']?\s*$`,
			description: "Container image uses latest tag in Kubernetes manifest",
			cwe:         "CWE-829", keywords: []string{":latest"},
			filePatterns: []string{"*.yaml", "*.yml"},
			tags:         []string{"iac", "kubernetes", "supply-chain"},
			remediation:  "Pin container images to specific versions or digests (e.g., 'nginx:1.25@sha256:abc...'). The latest tag is mutable and can silently introduce breaking changes.",
			references:   []string{"https://cwe.mitre.org/data/definitions/829.html"},
		},
		{
			id: "IAC-032", severity: findings.SeverityCritical, confidence: findings.ConfidenceMedium,
			pattern:     `(?i)\bcluster-admin\b`,
			description: "ClusterRoleBinding references cluster-admin role",
			cwe:         "CWE-269", keywords: []string{"cluster-admin"},
			filePatterns: []string{"*.yaml", "*.yml"},
			tags:         []string{"iac", "kubernetes", "rbac", "privilege"},
			remediation:  "Avoid binding to cluster-admin. Create custom ClusterRoles with minimum required permissions. cluster-admin grants unrestricted access to the entire cluster.",
			references:   []string{"https://cwe.mitre.org/data/definitions/269.html"},
		},
		{
			id: "IAC-033", severity: findings.SeverityMedium, confidence: findings.ConfidenceMedium,
			pattern:     `(?i)hostPort\s*:\s*\d+`,
			description: "Container specifies hostPort binding",
			cwe:         "CWE-284", keywords: []string{"hostport"},
			filePatterns: []string{"*.yaml", "*.yml"},
			tags:         []string{"iac", "kubernetes", "network"},
			remediation:  "Use Kubernetes Services (ClusterIP, NodePort, or LoadBalancer) instead of hostPort. hostPort bypasses network policies and limits pod scheduling.",
			references:   []string{"https://cwe.mitre.org/data/definitions/284.html"},
		},
		{
			id: "IAC-034", severity: findings.SeverityMedium, confidence: findings.ConfidenceLow,
			pattern:     `(?i)type\s*:\s*LoadBalancer`,
			description: "Service type LoadBalancer exposes service externally",
			cwe:         "CWE-284", keywords: []string{"loadbalancer"},
			filePatterns: []string{"*.yaml", "*.yml"},
			tags:         []string{"iac", "kubernetes", "network"},
			remediation:  "Verify that LoadBalancer exposure is intentional. Consider using an Ingress controller with TLS termination for HTTP services instead of direct LoadBalancer exposure.",
			references:   []string{"https://cwe.mitre.org/data/definitions/284.html"},
		},
		{
			id: "IAC-035", severity: findings.SeverityHigh, confidence: findings.ConfidenceHigh,
			pattern:     `(?i)runAsNonRoot\s*:\s*false`,
			description: "Kubernetes pod explicitly allows running as root",
			cwe:         "CWE-250", keywords: []string{"runasnonroot"},
			filePatterns: []string{"*.yaml", "*.yml"},
			tags:         []string{"iac", "kubernetes", "privilege"},
			remediation:  "Set runAsNonRoot: true and runAsUser to a non-zero UID. Running as root in a container increases the blast radius of container escapes.",
			references:   []string{"https://cwe.mitre.org/data/definitions/250.html"},
		},

		// =================================================================
		// GitHub Actions rules (IAC-011 to IAC-018)
		// =================================================================
		{
			id: "IAC-011", severity: findings.SeverityCritical, confidence: findings.ConfidenceMedium,
			pattern:     `(?i)pull_request_target\s*:`,
			description: "GitHub Actions workflow uses pull_request_target trigger",
			cwe:         "CWE-94", keywords: []string{"pull_request_target"},
			filePatterns: []string{"*.yml", "*.yaml"},
			tags:         []string{"iac", "github-actions", "ci-cd"},
			remediation:  "Avoid pull_request_target unless absolutely necessary. It runs with write permissions in the context of the base branch, enabling script injection from fork PRs.",
			references:   []string{"https://cwe.mitre.org/data/definitions/94.html", "https://securitylab.github.com/research/github-actions-preventing-pwn-requests/"},
		},
		{
			id: "IAC-012", severity: findings.SeverityCritical, confidence: findings.ConfidenceHigh,
			pattern:     `\$\{\{\s*github\.event\.(issue|comment|pull_request|review|discussion)\.(title|body|head\.ref|label)`,
			description: "Workflow uses untrusted event data in expression (script injection risk)",
			cwe:         "CWE-77", keywords: []string{"github.event"},
			filePatterns: []string{"*.yml", "*.yaml"},
			tags:         []string{"iac", "github-actions", "injection"},
			remediation:  "Never use github.event properties directly in run: steps. Pass them through an environment variable and quote properly, or use an action input.",
			references:   []string{"https://cwe.mitre.org/data/definitions/77.html", "https://securitylab.github.com/research/github-actions-untrusted-input/"},
		},
		{
			id: "IAC-013", severity: findings.SeverityHigh, confidence: findings.ConfidenceMedium,
			pattern:     `(?i)uses:\s*[a-zA-Z0-9._-]+/[a-zA-Z0-9._-]+@(v\d|main|master|latest|develop|HEAD)`,
			description: "GitHub Action pinned to mutable tag instead of commit SHA",
			cwe:         "CWE-829", keywords: []string{"uses:"},
			filePatterns: []string{"*.yml", "*.yaml"},
			tags:         []string{"iac", "github-actions", "supply-chain"},
			remediation:  "Pin third-party actions to a full commit SHA (e.g., actions/checkout@a5ac7e...). Mutable tags can be moved to point to different, potentially malicious code.",
			references:   []string{"https://cwe.mitre.org/data/definitions/829.html", "https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions"},
		},
		{
			id: "IAC-014", severity: findings.SeverityHigh, confidence: findings.ConfidenceHigh,
			pattern:     `(?i)permissions\s*:\s*write-all`,
			description: "GitHub Actions workflow has write-all permissions",
			cwe:         "CWE-269", keywords: []string{"write-all"},
			filePatterns: []string{"*.yml", "*.yaml"},
			tags:         []string{"iac", "github-actions", "privilege"},
			remediation:  "Use granular permissions instead of write-all. Specify only the required scopes (e.g., contents: read, issues: write) following the principle of least privilege.",
			references:   []string{"https://cwe.mitre.org/data/definitions/269.html", "https://docs.github.com/en/actions/security-guides/automatic-token-authentication"},
		},
		{
			id: "IAC-015", severity: findings.SeverityHigh, confidence: findings.ConfidenceHigh,
			pattern:     `(?i)(echo|printf)\s+.*\$\{\{\s*secrets\.`,
			description: "Secret value printed to GitHub Actions workflow logs",
			cwe:         "CWE-532", keywords: []string{"secrets."},
			filePatterns: []string{"*.yml", "*.yaml"},
			tags:         []string{"iac", "github-actions", "secrets"},
			remediation:  "Never echo secrets to logs. GitHub masks known secrets but may miss transformations. Pass secrets directly to the command that needs them via environment variables.",
			references:   []string{"https://cwe.mitre.org/data/definitions/532.html"},
		},
		{
			id: "IAC-016", severity: findings.SeverityMedium, confidence: findings.ConfidenceMedium,
			pattern:     `(?i)runs-on\s*:\s*\[?\s*self-hosted`,
			description: "GitHub Actions workflow uses self-hosted runner",
			cwe:         "CWE-284", keywords: []string{"self-hosted"},
			filePatterns: []string{"*.yml", "*.yaml"},
			tags:         []string{"iac", "github-actions", "infrastructure"},
			remediation:  "Self-hosted runners persist state between jobs and may be shared across repositories. Use ephemeral runners, restrict with labels, and never use on public repositories.",
			references:   []string{"https://cwe.mitre.org/data/definitions/284.html", "https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners/about-self-hosted-runners"},
		},
		{
			id: "IAC-017", severity: findings.SeverityMedium, confidence: findings.ConfidenceHigh,
			pattern:     `::set-output\s+name=`,
			description: "Workflow uses deprecated set-output command",
			cwe:         "CWE-77", keywords: []string{"set-output"},
			filePatterns: []string{"*.yml", "*.yaml"},
			tags:         []string{"iac", "github-actions", "deprecated"},
			remediation:  "Replace ::set-output with $GITHUB_OUTPUT environment file. The set-output command is deprecated and vulnerable to log injection attacks.",
			references:   []string{"https://cwe.mitre.org/data/definitions/77.html", "https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/"},
		},
		{
			id: "IAC-018", severity: findings.SeverityLow, confidence: findings.ConfidenceMedium,
			pattern:     `(?i)continue-on-error\s*:\s*true`,
			description: "Workflow step suppresses failures with continue-on-error",
			cwe:         "CWE-755", keywords: []string{"continue-on-error"},
			filePatterns: []string{"*.yml", "*.yaml"},
			tags:         []string{"iac", "github-actions", "error-handling"},
			remediation:  "Avoid continue-on-error: true as it can mask security check failures. If needed, check the step outcome explicitly and fail on security-critical errors.",
			references:   []string{"https://cwe.mitre.org/data/definitions/755.html"},
		},

		// =================================================================
		// Docker Compose rules (IAC-019 to IAC-021)
		// =================================================================
		{
			id: "IAC-019", severity: findings.SeverityCritical, confidence: findings.ConfidenceHigh,
			pattern:     `(?i)privileged\s*:\s*true`,
			description: "Docker Compose service runs in privileged mode",
			cwe:         "CWE-250", keywords: []string{"privileged"},
			filePatterns: []string{"docker-compose*.yml", "docker-compose*.yaml", "compose*.yml", "compose*.yaml"},
			tags:         []string{"iac", "docker-compose", "privilege"},
			remediation:  "Remove privileged: true. Use specific cap_add entries for required capabilities. Privileged mode gives the container full host access.",
			references:   []string{"https://cwe.mitre.org/data/definitions/250.html"},
		},
		{
			id: "IAC-020", severity: findings.SeverityHigh, confidence: findings.ConfidenceHigh,
			pattern:     `(?i)network_mode\s*:\s*["']?host["']?`,
			description: "Docker Compose service uses host network mode",
			cwe:         "CWE-284", keywords: []string{"network_mode"},
			filePatterns: []string{"docker-compose*.yml", "docker-compose*.yaml", "compose*.yml", "compose*.yaml"},
			tags:         []string{"iac", "docker-compose", "network"},
			remediation:  "Use bridge networking (default) or custom networks instead of host mode. Host networking bypasses Docker's network isolation.",
			references:   []string{"https://cwe.mitre.org/data/definitions/284.html"},
		},
		{
			id: "IAC-021", severity: findings.SeverityCritical, confidence: findings.ConfidenceHigh,
			pattern:     `(?i)/var/run/docker\.sock`,
			description: "Docker Compose service mounts Docker socket",
			cwe:         "CWE-250", keywords: []string{"docker.sock"},
			filePatterns: []string{"docker-compose*.yml", "docker-compose*.yaml", "compose*.yml", "compose*.yaml"},
			tags:         []string{"iac", "docker-compose", "privilege"},
			remediation:  "Avoid mounting the Docker socket. It gives the container full control over the Docker daemon, equivalent to root access on the host. Use Docker-in-Docker or rootless alternatives.",
			references:   []string{"https://cwe.mitre.org/data/definitions/250.html"},
		},

		// =================================================================
		// Helm / K8s packaging (IAC-046 to IAC-050)
		// =================================================================
		{
			id: "IAC-046", severity: findings.SeverityCritical, confidence: findings.ConfidenceHigh,
			pattern:     `(?i)name\s*:\s*tiller|image\s*:.*tiller`,
			description: "Tiller (Helm v2) deployment detected",
			cwe:         "CWE-269", keywords: []string{"tiller"},
			filePatterns: []string{"*.yaml", "*.yml"},
			tags:         []string{"iac", "helm", "deprecated", "privilege"},
			remediation:  "Migrate to Helm v3 which removed Tiller. Tiller runs with cluster-admin privileges and is a well-known attack target in Kubernetes clusters.",
			references:   []string{"https://cwe.mitre.org/data/definitions/269.html", "https://helm.sh/docs/faq/changes_since_helm2/"},
		},
		{
			id: "IAC-047", severity: findings.SeverityHigh, confidence: findings.ConfidenceMedium,
			pattern:     `(?im)^(admin_?password|root_?password|master_?password)\s*:\s*["']?[a-zA-Z0-9_!@#$%^&*]{4,}["']?\s*$`,
			description: "Default or hardcoded admin password in Helm values",
			cwe:         "CWE-798", keywords: []string{"admin_password", "root_password", "master_password"},
			filePatterns: []string{"values.yaml", "values.yml", "values*.yaml", "values*.yml"},
			tags:         []string{"iac", "helm", "secrets"},
			remediation:  "Never hardcode passwords in Helm values files. Use Kubernetes Secrets, external secret managers (Vault, SOPS), or Helm --set flags for sensitive values.",
			references:   []string{"https://cwe.mitre.org/data/definitions/798.html"},
		},
		{
			id: "IAC-048", severity: findings.SeverityHigh, confidence: findings.ConfidenceMedium,
			pattern:     `(?i)rbac\s*:\s*\n\s*(create|enabled)\s*:\s*false`,
			description: "Helm chart disables RBAC",
			cwe:         "CWE-269", keywords: []string{"rbac"},
			filePatterns: []string{"values.yaml", "values.yml", "values*.yaml", "values*.yml"},
			tags:         []string{"iac", "helm", "rbac"},
			remediation:  "Enable RBAC in Helm values. Disabling RBAC removes access control from the deployed application, allowing any authenticated user full access.",
			references:   []string{"https://cwe.mitre.org/data/definitions/269.html"},
		},
		{
			id: "IAC-049", severity: findings.SeverityHigh, confidence: findings.ConfidenceHigh,
			pattern:     `(?i)pid\s*:\s*["']?host["']?`,
			description: "Docker Compose service shares host PID namespace",
			cwe:         "CWE-250", keywords: []string{"pid"},
			filePatterns: []string{"docker-compose*.yml", "docker-compose*.yaml", "compose*.yml", "compose*.yaml"},
			tags:         []string{"iac", "docker-compose", "privilege"},
			remediation:  "Remove pid: host. Sharing the host PID namespace lets the container see and interact with all host processes, breaking process isolation.",
			references:   []string{"https://cwe.mitre.org/data/definitions/250.html"},
		},
		{
			id: "IAC-050", severity: findings.SeverityMedium, confidence: findings.ConfidenceMedium,
			pattern:     `(?i)disable_security\s*[:=]\s*true|skip_security_checks?\s*[:=]\s*true|security_enabled\s*[:=]\s*false`,
			description: "CI/CD configuration disables security checks",
			cwe:         "CWE-693", keywords: []string{"disable_security", "skip_security", "security_enabled"},
			filePatterns: []string{"*.yml", "*.yaml", "*.toml", "*.cfg"},
			tags:         []string{"iac", "ci-cd", "configuration"},
			remediation:  "Never disable security checks in CI/CD pipelines. If a check is failing, fix the underlying issue rather than disabling the check.",
			references:   []string{"https://cwe.mitre.org/data/definitions/693.html"},
		},
	}

	out := make([]rules.Rule, len(defs))
	for i, d := range defs {
		out[i] = rules.Rule{
			ID:           d.id,
			Version:      "1.0",
			Description:  d.description,
			Severity:     d.severity,
			Confidence:   d.confidence,
			MatcherType:  "regex",
			Pattern:      d.pattern,
			FilePatterns: d.filePatterns,
			Keywords:     d.keywords,
			Tags:         d.tags,
			Metadata:     map[string]string{"cwe": d.cwe},
			Remediation:  d.remediation,
			References:   d.references,
		}
	}
	return out
}
