package taintflow

import (
	"context"
	"testing"

	"github.com/nox-hq/nox/core/discovery"
)

// TestGeneratedFilesAreSkipped: a flow in a generated file is not this
// repository's code; the same flow hand-written is reported.
func TestGeneratedFilesAreSkipped(t *testing.T) {
	flow := "import os\nfrom flask import request\ndef h():\n    os.system(request.args.get('c'))\n"
	for _, c := range []struct {
		name, content string
		want          int
	}{
		{"hand-written", flow, 1},
		{"generated banner", "# Code generated by protoc. DO NOT EDIT.\n" + flow, 0},
	} {
		dir := t.TempDir()
		art := writeArtifact(t, dir, "h.py", c.content)
		fs, err := NewAnalyzer().ScanArtifacts(context.Background(), []discovery.Artifact{art})
		if err != nil {
			t.Fatal(err)
		}
		if got := len(fs.Findings()); got != c.want {
			t.Errorf("%s: %d findings, want %d", c.name, got, c.want)
		}
	}
}
